### ISSUE TITLE
Bug with HTML view in Blocks

### ISSUE THREAD

**Issue by GRMacGeek** [yuzoolcode/pulsecms-tracking#1]
when editing a block and clicking "html", the text runs outside the editing window.
![pulse_cms-html view](https://user-images.githubusercontent.com/6706155/33769214-538dded8-dbf7-11e7-914c-2be4a02e3d17.jpg)

**Comment by oliver-77** [comment]
If I try that, I have a horizontal scrollbar at the bottom. (Windows 10, Chrome, Opera, Firefox)

![scrollbar](https://user-images.githubusercontent.com/24696577/33769437-8a78dc3a-dc2a-11e7-97fd-ffebb7bd5a51.png)

**Comment by IvaRoSoft** [comment]
My Chrome login.
![admin - 8_12](https://user-images.githubusercontent.com/29908185/33770121-d57fe956-dc2c-11e7-9803-8cf5b14a859e.png)

**Comment by ghost** [comment]
@GRMacGeek - there's nothing we can do about that at the moment, it's a bug in Redactor and CodeMirror integration - it would be better if it was prettified and added line-breaks

@IvaRoSoft this looks like a different thing... CSS sheets seem missing. Is this Chrome only?

**Comment by IvaRoSoft** [comment]
(Chrome) Home Screen.
Firefox Developer is OK.
Pulse, does not overwrite the contact form (change the text).
The form does not send an email.
I set the OTP password, = Could not sign in.
New installation.
Editing the start page has a dimension
  "Max-width: 1000px;) = this is not enough.
Edit:
inline edit.css
.pulsecore-inline-edit
.pulsecore-inline-edit-content
...........
That's just the beginning.
![fronted1 - 8_12 002](https://user-images.githubusercontent.com/29908185/33772031-7fcd8962-dc33-11e7-8c6c-0f60dbc7f4a8.png)

**Comment by IvaRoSoft** [comment]
This is Firefox.
Send an email.
![email - 8_12 002](https://user-images.githubusercontent.com/29908185/33772617-87d9fa44-dc35-11e7-9259-648442ffe132.png)

**Comment by jrondorf** [comment]
@ivarosoft 
You are mixing issues. Please create a new issue for each of your problems. Thanks.

**Comment by ghost** [comment]
Thanks @IvaRoSoft - yeah can you make multiple issues in this GitHub so 1 issue per issue :)
Thanks!

**Comment by ghost** [comment]
Solution for this might be to just go back to the original one we had in 4 with line breaks (no code mirror colours) until they create a solution

**Comment by GRMacGeek** [comment]
That sounds like a good idea to me! Unusable without line breaks right now.

**Comment by ghost** [comment]
And Redactor 3 out next year might have a better integration we can look forward to

**Comment by GRMacGeek** [comment]
Actually, I would rather have Redactor 2 than Redactor 1, seeing as Redactor 2 at least has other formatting options for the end users, especially the inline editing. Just have to let them know to stay away from the HTML view for now.

**Comment by jrondorf** [comment]
We already have the latest Redactor 2 version in place.

**Comment by ghost** [comment]
Yes and latest / latest was added in 5.0.1 (Redactor 2.12)

**Comment by ghost** [comment]
Will be fixed in Redactor 3. But means going back to the black and no code highlighting as they've dropped this plugin (maybe because of these issues)

**Comment by ghost** [comment]
Redactor 3 added for Pulse 5.1
