### ISSUE TITLE
Dates in blog

### ISSUE THREAD

**Issue by ghost** [yuzoolcode/pulsecms-tracking#10]
https://forum.pulsecms.com/t/blog-dates-show-unknown-on-front-end/865

**Comment by GRMacGeek** [comment]
Not sure if this needs a separate issue, but in the blogs, you can’t choose dates in the past... This would be useful when migrating old blog posts.

**Comment by ghost** [comment]
Yes this was added as a fail safe but noted for an update 👍 
https://forum.pulsecms.com/t/blog-post-prior-date-not-permitted/862

**Comment by ghost** [comment]
Fixed in 5.0.2! 😃👍
http://help.pulsecms.com/article/10-version-history
