### ISSUE TITLE
Adding a user Group breaks Pulse

### ISSUE THREAD

**Issue by junction10** [yuzoolcode/pulsecms-tracking#100]
I was trying to create a new user for debugging purposes, so wanted the user to have R/W access to a single file, with Read access to all the rest..  
I tried creating the user (logical step) first but it said to create a group to add the user to..

So I created a new group..  however - as SOON as the new group is created, my site, built with Rapidweaver, won't display ANY Pulse content again..  not until I delete the group I just created...  

Is users/Groups still a beta?

**Comment by ghost** [comment]
No not in BETA, will need to test this, thanks for the report

**Comment by junction10** [comment]
It seems I can't add a user, without first creating a group - it's the creation of the group that breaks the display of blocks..  (The blog will display, but no 'block' content elsewhere on the site.

If I create a group, I can then create a new user, choosing the group I just created and assigning the user to that group..  the blocks content still won't display..  even though read/write access was granted.

I can then delete the group, and the blocks content will then display on the site again..  
It also leaves the user - so the user can log in as either admin or editor...  but the read/write permissions for each page/block when creating the user group do not apply to the user any more..  
So if I choose READ access for all but just one block for example, after deleting the user group, the user group name still shows next to the user name in the admin panel->settings->extend>Manager user list ....  but the permissions obviously don't, as the group has been deleted, along with any permissions set...

So at least I can set up individual users for my client - but at the moment, I can't restrict them from being able to edit only specific bits of content...

I can prevent them accessing the Pulse settings though, as I can still assign them as Admin or Editor (or User?)...


Just done a bit more testing...  I can create a user group, and as long as I don't select ANY 'Pages' for READ or READ/WRITE access (ie: Leave the radio buttons unselected), then it doesn't break blocks display..  If I choose them all to be read access, then the blocks stop displaying again.

Also just tried creating a 'user' and assigning to the group I just created, which had READ access to most of the blocks and READ/WRITE access to a handful..  and NONE of the pages selected for R or R/W access..   When I logged in as the user, I could still READ and WRITE every single block - not just the ones I'd only assigned R/W access to...

So the user creation at the moment only works as far as preventing someone from accessing the SETTINGS page...

J.

**Comment by ghost** [comment]
Thanks for this report.

We have checked the user/group creation code and can't replicate this bug. That said, I think we need a little more info, specifically:

- error logs, if any - can you attach those here?
- the sequence of steps in creating the group (maybe let us test your new work flow from as above)

This is a strange bug... 

Is this the most recent pulse release 5.3.1?

**Comment by junction10** [comment]
Can I email you some login details & password - you can have a look around the server if you like, see what happens on my server when you create a new usergroup and user..  See if you can spot what's going wrong?  It's a live server, but it's a test one.
I'll set you up FTP access too if that helps.

**Comment by ghost** [comment]
You can DM me on the forum. 
And if you could attach logs (private message is also fine) that would really help also :) 

thanks

**Comment by junction10** [comment]
I've sent you a DM on the pulse forum..  Thanks Michael.

**Comment by ghost** [comment]
Thanks @junction10 !

For the user groups:
- there's not much option but to allow content to be visible unless it's access controlled in a group. Otherwise there would need to be a public read group which would need to be updated when any content changes.

- the page not showing after being added bug has been fixed. This will be in 5.3.2. 
The entry was added, just not showing on the page.
