### ISSUE TITLE
Feature Request: Better usability handling after uploading media

### ISSUE THREAD

**Issue by oliver-77** [yuzoolcode/pulsecms-tracking#101]
I have noticed that it is a bit awkward to get back into the folder when you have uploaded media files.
At the moment you have to click on media in the menu again and then select the folder.
This is always annoying when you create a folder for galleries and want to return to the folder to copy the tag.

Okay you could always press the back button of the browser but is that the right way?

Just an idea:

![media](https://user-images.githubusercontent.com/24696577/55558222-ea512300-56eb-11e9-85e5-ab592cc20836.png)

**Comment by ghost** [comment]
- Improved usability handling after uploading an image
This is ready for 5.3.3 👍
