### ISSUE TITLE
A better way to add / manage 'Featured Images' when creating a blog post

### ISSUE THREAD

**Issue by ezchile** [yuzoolcode/pulsecms-tracking#103]
When composing a blog post, it would be really beneficial to be able to view, upload and select which image is used as that posts 'featured image'.  Having to put them in a certain directory, or rename either the image or post in a certain way seems really odd and unintuitive.  Even spawning the Media section in another tab involves lots of renaming and copying and pasting.  There must be a more user-friendly way.

Even if the upload etc. is handled by the Media handling that already exists, there should be a way to locate an image you want to associate/change association with per post, and the path to the asset saved with the entry.  If that 'selected featured image path' entry exists, use that path to the file, if not, use the same mechanism as now, if neither exist, show nothing as the blog entry doesn't have a featured image.

Other blogging platforms have this feature and it really seems lacking in Pulse.

**Comment by ghost** [comment]
Double discussion:
https://forum.pulsecms.com/t/recent-post-visual/1458/7

**Comment by ghost** [comment]
It should be possible to add another field to the blog storage object with the featured image. The selection widget would be a popup with the gallery list and selecting a gallery shows the thumbnails available.

What should happen to the old feature image code though ? This will need to be thought through well before proceeding.

**Comment by ghost** [comment]
We've started on this for the next update (5.3.3) - it will come with a popup and image selector.

**Comment by ghost** [comment]
Preview of how this is looking 🤩

![CleanShot 2019-05-18 at 07 44 36](https://user-images.githubusercontent.com/4608547/57959968-4d67e380-7941-11e9-8e85-95b8d30ae20e.gif)

**Comment by ezchile** [comment]
Looks great!

**Comment by ghost** [comment]
This now also has a + opener button added also

It's ready for 5.3.3!
