### ISSUE TITLE
Re-ordering images when lots of images exist in the folder.

### ISSUE THREAD

**Issue by ezchile** [yuzoolcode/pulsecms-tracking#104]
If folders contain many images (enough to require pagination), being able to reorder them in any meaningful way seems not to really work.  For instance, upload 15 images into a folder. try to reorder the last image (on page 2) so that it comes first of all.. (so, basically on page 1)

There seems to be no way to be able to move between pages.

Could something like a dropdown be created to 'send image to page (however many pages are in the pagination)' be developed?

**Comment by ghost** [comment]
Good use case

The setting in admin for "Pagination" and "Results per page" should allow more in the meantime.

But good idea for cross-page ordering

**Comment by ghost** [comment]
One option is to make the sort field visible. Perhaps as a select box.

**Comment by ghost** [comment]
- Re-ordering of images in media can now be dragged and dropped (great for when lots of images exist) with drop targets for next/previous pages

This is done and added for 5.3.3
This works well and  it avoids having to use select boxes for multi-page sorting.

Video example:
https://imgur.com/a/wdnoE36
