### ISSUE TITLE
Pictures does not scale proportionally

### ISSUE THREAD

**Issue by Karmeshvar** [yuzoolcode/pulsecms-tracking#105]
Hello I am experiencing a very strange problem with Pulse. Photos or pictures does not scale proportionally when changing screen size or device. They scale correctly on desktop computers with full screen. But on smaller screen sizes they distort.
Link to the affected page/pages: http://www.ingemann-selskabet.dk/styled-9/Langt/1789-1800/

Kind Regards

Kent

**Comment by ghost** [comment]
Thanks Kent

- Did you change the size of the images in the Pulse editor?

Try this solution:

- add this to your RapidWeaver settings (site wide CSS) and republish the site:

```
img {
height: auto!important;
}
```

That seems to fix it:

![CleanShot 2019-04-24 at 22 13 23](https://user-images.githubusercontent.com/4608547/56662107-346f6800-66de-11e9-8b7b-d5e1d2b1219d.jpg)

**Comment by Karmeshvar** [comment]
Hello Sir

Yes thanks a lot, that fixed the problem. And the author of the content on the website resize them in Pulse. But now everything is working like a charm. :-)
Kind Regards
Kent

**Comment by ghost** [comment]
Great - glad to hear it :)
