### ISSUE TITLE
Dropzone is missing icon in version 5.3.1 & 5.3.2

### ISSUE THREAD

**Issue by AceTutor** [yuzoolcode/pulsecms-tracking#106]
**Icon Missing in Dropzone**
Sorry not to have noticed this earlier. Version 5.2.4 works fine but the changes made in vs 5.3.1 and vs 5.3.2 result in a box without the cloud upload icon. 

Rather than wait for the next update can I ask that you provide a patch file/s once resolved.  

Thanks for a great product.

**Comment by ghost** [comment]
Thanks - will need to test this

Can't imagine what it is without taking a testing look - could be something along the lines of the Font Awesome not loading correctly - the web inspector in the browser might give you a clue for now

**Comment by AceTutor** [comment]
Thanks Michael for prompt response overnight.
Please check out my live test page at [https://www.gcmfc.com.au/pulse-5.3.2/test-pulse](https://www.gcmfc.com.au/pulse-5.3.2/test-pulse)
Here is a totally clean install of v5.3.2 - I've only changed the timezone & front-end editing otherwise everything is original. To test Dropzone I have added one extra image to gallery1.
Please test it for yourself. 
I await your conclusions and hopefully an early resolution.
Cheers John

**Comment by ghost** [comment]
![CleanShot 2019-05-07 at 07 05 45](https://user-images.githubusercontent.com/4608547/57258158-8f1da200-7096-11e9-9527-ceb7932caa8d.jpg)

The icon has changed in FA 5

The solution is to change the reference to the icon to `class="fa fa-cloud-upload-alt fa-3x"`

Add "-alt" 
https://fontawesome.com/icons/cloud-upload-alt?style=solid

Change on line 142:
inc/plugins/drop/dropzone.js

**Comment by ghost** [comment]
- this has been added to the codebase for next release
- I'll close this but if your test doesn't work then please re-open
- let me know!

**Comment by AceTutor** [comment]
Thanks - solved beautifully. Appreciate rapid solution.
