### ISSUE TITLE
Inline Editing / Rapidweaver not working?

### ISSUE THREAD

**Issue by GRMacGeek** [yuzoolcode/pulsecms-tracking#107]
it seems "inline editing" with Rapidweaver doesn't work anymore. 
I just updated a site to the latest builds of Pulse 5.3.2 - [https://www.vocon.ca](https://www.vocon.ca) and inline edit used to work on this site, but doesn't anymore.

- I noticed that somebody else posted this issue in the Pulse Forum and a Foundry project, this one is a Foundation Project

Also question: 

- What does the "P5 Inline edit" stack do? There is no documentation for it, and I tried wrapping stacks with it to see if maybe this would fix the issue, but it doesn't seem to do anything at all.

Thanks!

**Comment by jrondorf** [comment]
I think we already discussed this inline edit stack. This is required for all framework themes like Foundation. Put the content you want do edit into this stack and enable inline edit, but not globally.

**Comment by GRMacGeek** [comment]
Okay... I have disabled "global inline edit" in the "P5 Integration Stack" and checked "Enable Inline Edit"

- I tried wrapping everything in the page in the "inline edit" stack
- I tried just using it around individual stacks

and still no inline edit working on the website... 

I do apologize if this was discussed at some point, but I don't build new sites this way anymore, just updating existing ones. The steps keep changing, but your documentation doesn't match the changes, and doesn't say anything about how to make this work...

**Comment by GRMacGeek** [comment]
While we are fixing little things - I notice the "P5 Blog" stack is missing `<<blog-item-title>>` which is part of the default tag

**Comment by jrondorf** [comment]
Yeah, the blog-item-title was added recently in the Pulse backend. I will add this to the stack to. 

As you are able to use the tags right away inside RW, you can specify this directly there.

The inline edit stack was added just for you to make the navigation of Foundation not editable. I will update the docu and check what changed. 

Thanks.

**Comment by ghost** [comment]
Thanks for reporting @GRMacGeek 

- I think the Inline Editing in RapidWeaver is working, I remember there was some changes but the Stacks were patched. 
- The <<blog-item-title>> was an oversight on my part and @jrondorf will get that in the Stack soon but feel free to do the custom code pasting for now!

Cheers!

**Comment by jrondorf** [comment]
Just added the blog-item-title tag inside the blog stack (v5.3.0)

Inline edit works great with the latest of the greatest Pulse 5.3.2.

Demo file of pulse5.instacks.com where this was retested: https://pulse5.instacks.com/6926C152-1E7F-403A-8C16-C4DFE109DF15_rwbackup/demo_pulsecmsstack5.rw8.zip

Screenshot of the blog page with inline edit enabled:

![RapidWeaver 2019-05-19 at 14 50 50](https://user-images.githubusercontent.com/2099795/57982483-60181080-7a46-11e9-9d8a-7dfd84f16c6f.png)

**Comment by jrondorf** [comment]
Try to 
- clean browser cache with cookies
- restart browser (in my case chrome)
- navigate to https://www.vocon.ca first
- afterwards to https://www.vocon.ca/pulse/admin
- login
- and back to https://www.vocon.ca

**Comment by GRMacGeek** [comment]
Cool got it working again on this site.

- One thing you will want to note in the documentation is only use 1 inline edit stack on each page. If you try and use more than one, it only shows the the edit areas of the top stack on the page.

**Comment by jrondorf** [comment]
> One thing you will want to note in the documentation is only use 1 inline edit stack on each page.

Done
