### ISSUE TITLE
Blocs and referencing "Pulse Blocks" that are in folders

### ISSUE THREAD

**Issue by GRMacGeek** [yuzoolcode/pulsecms-tracking#108]
Okay - putting the Pulse installation in a sub-folder looks like it is fixed with the latest betas, thanks all!

However, being able to specify a "folder" for individual "Pulse Blocks" has not. I am going to submit a "bug request" at Cazoobi as well

**Here is what I mean:**

Right now when you add a "Pulse Brick" in Blocs - you add a "Block ID" but there is no way to reference a folder, so every "Pulse Block" has to be in the root "Blocks Folder" in your "Pulse Dashboard..." This is unwieldy for large websites... 

![Blocs_and_content](https://user-images.githubusercontent.com/6706155/59162980-36438e00-8ac8-11e9-81c1-24985908952d.jpg)

![Pulse_CMS](https://user-images.githubusercontent.com/6706155/59162982-3a6fab80-8ac8-11e9-9955-baf0de94521a.jpg)

It is far easier to have the content in "folders" in  the Pulse Blocks folder. Blocs already does this with the "main" folder it creates, and in programs like Rapidweaver all we do is add a "/" between the "folder name" and "block ID" so in the example in the attached pictures in Blocs

- I tried to enter "catalogs/2-2-middle" as the "Block ID"
- but Blocs won't accept this input, and changes it to "catalogs-2-2-middle"

For a "workaround" I have been using "HTML Widgets" in Blocs instead (pic attached of one of the other pages) but it would be nice to be able to do this in the "Pulse Brick" instead

![Blocs-worlaround](https://user-images.githubusercontent.com/6706155/59163015-fb8e2580-8ac8-11e9-81d0-153787075592.jpg)

**Comment by ghost** [comment]
HTML widgets in Blocs is a good work around @GRMacGeek  - but you're right, it's most likely the ID input restricting the "/" character. Am sure this will be a simple-ish fix :) 

Thanks for reporting
