### ISSUE TITLE
masonry gallery needs updating

### ISSUE THREAD

**Issue by GRMacGeek** [yuzoolcode/pulsecms-tracking#109]
The "masonry gallery" that is included with the Pulse install doesn't work properly but if you 

- replace the masonry.php --> inc/tags
- and gal_masonry.phtml --> pulsecore/template/tags
- with the one found here https://addons.pulsecms.com/p/mgp5x

it works just fine. This one needs to be included in the Pulse Install package

**Comment by ghost** [comment]
Thanks for reporting - will test!

**Comment by ghost** [comment]
Masonry library has been replaced by flexbox - have also tweaked the CSS should this should be fine now.

Will be in 5.3.5
