### ISSUE TITLE
Bug Bounty Program

### ISSUE THREAD

**Issue by JAO-cyber** [yuzoolcode/pulsecms-tracking#110]
Good day,

I'm Joshua Osabel, a web security researcher.

Is there a way to submit a report for a security vulnerability on your site or on your software?

If you don't have a bounty program, 
Do you also give a reward for a vulnerability that will be reported to your technical team?

Your response would be highly appreciated.

Thanks! 

joshuaosabel45@gmail.com
joshua osabel

**Comment by JAO-cyber** [comment]
That didnt answer my question

**Comment by ghost** [comment]
- You can report bugs here in this thread
- We don't have a bounty programme

**Comment by JAO-cyber** [comment]
But will you give rewards ?

**Comment by ghost** [comment]
Sorry, not at this time.
