### ISSUE TITLE
Pulse Commerce - Request for Function

### ISSUE THREAD

**Issue by davchy** [yuzoolcode/pulsecms-tracking#111]
Hello,
adding Commerce is great! Unfortunately, offline payment is very widespread in Central Europe. By contrast, in the Czech Republic, PayPal is minimally used by the general population. I want to get a Pulse license for designers, but I'm reluctant because of the absence of other options.
It would be great if other standard options were added, namely: 

- **Cash on delivery** (Ideally with the option to set a fee for this type of payment.) 
- **Bank Transfer Payment** (For this case, you must generate a unique numeric identifier for each order and display it in the payment instructions. The number must not be more than 10 characters, and it could be used as a variable symbol (in the Czech Republic and Slovakia) or as a message for the recipient / in other countries / https://en.wikipedia.org/wiki/Variable_symbol.)

Furthermore, I see the necessity of **my own definition of several carriers** and the setting of a general price for each carrier (to be used if the shipping price is not set for the item).

And last but not least, it is necessary to **comply with GDPR** - when in the **ORDER PROCESS** the customer must confirm the policy of processing personal data and a link to this document must be provided at the checkbox. Otherwise, the site owner would violate the law by offering European Union customers.

Sorry, English is not my native language. Perhaps everything was clear :)

Regards,
David

**Comment by ghost** [comment]
Thanks @davchy 

- thanks for the request for more payment options, we will look into it
- in most situations, PayPal allow credit card processing without a PayPal account so buyers won't need to use PayPal, but worth checking in each country 
- there are other integrations of Ecommerce - this is is just the one we have made. For example Snipcart and Paddle also exist and you may prefer to use those?
- Shipping is also simple at the moment with one shipping price per item
- I think the checkbox was mentioned previously (https://forum.pulsecms.com/t/pulse-ecommerce-final-release/1370/11). We will look to add this in a future version but for now you could add this on the Store page anywhere with some custom HTML

Thanks David and hope that helps for now!

**Comment by davchy** [comment]
@yuzoolcode 
Thank you for answer.

Yes, I know about other integration - but that means not only the cost of Pulse, but also the cost of a third party SaaS.
I liked Pulse because it has "all under one roof". It is one of the aspects I consider when choosing the final CMS product.

If the offline payment functions (COD and bank transfer) are introduced + the possibility of individually adding carriers (and setting the transport price to a particular carrier) - then I'm decided to Pulse.

I'm sure many of your other customers (and potential ones) will appreciate these features.

Regards,
David

**Comment by ghost** [comment]
> I liked Pulse because it has "all under one roof". It is one of the aspects I consider when choosing the final CMS product.

Yes that's why we are doing our best to provide this :) 

Please keep an eye on our updates on our forum and updates page:
- http://forum.pulsecms.com
- https://www.pulsecms.com/latest/

Not sure when we can make such features but we will bear them in mind for a future update for sure!
