### ISSUE TITLE
Blog "Featured Images" can't access image folders

### ISSUE THREAD

**Issue by GRMacGeek** [yuzoolcode/pulsecms-tracking#113]
in Pulse 5.3.5

- When you try to add a "featured image" to a post, you can't access the folders in the Media folder, just brings up "question marks" (see attached photo)

![Featured Images](https://user-images.githubusercontent.com/6706155/62722660-f53efb80-b9dc-11e9-8bf0-0162686b9cb4.png)

**Comment by ghost** [comment]
I can't replicate - works for me....

<img width="1119" alt="Screenshot 2019-09-29 at 11 51 02" src="https://user-images.githubusercontent.com/4608547/65825222-892b9600-e2af-11e9-8df0-987d65a70f21.png">
<img width="1119" alt="Screenshot 2019-09-29 at 11 51 12" src="https://user-images.githubusercontent.com/4608547/65825223-89c42c80-e2af-11e9-8ca1-f7e46def503d.png">
<img width="1119" alt="Screenshot 2019-09-29 at 11 51 24" src="https://user-images.githubusercontent.com/4608547/65825224-89c42c80-e2af-11e9-80b3-73b5f0c64959.png">

- are those images present in the folder on the server?
- those are the default images that have been deleted?

**Comment by junction10** [comment]
Michael - I'm not sure that's where @GRMacGeek's issue is - you seem to be just inserting an image into the blog post itself in your screenshots..

I think @GRMacGeek is referring to the Meta section, if you click the meta button and then click to add Blog Featured Image...  try that?

Also @GRMacGeek - Perhaps it's a permissions issue?  Have you run the 'install.php' script to check the folder permissions are correct?  Can you also check those broken image icons are actually folders, and not, as I suspect, none-image document files, like PDF's etc?  I have a number of PDF's and DOC files that show up like that, so would be nice to filter out non web browsable images in certain areas..  

@yuzoolcode - I'm not experiencing EXACTLY the same issue, but it is only showing 2 folders in my media folder, and not all 6 that are there..  does it filter folders for Pulse system, like Thumbnails, Icons etc?  I can only see /Resources and /Featured_Images when inserting an image into a blog post OR adding a blog featured image from the META section..  
If I do click one of the sub folders that I can see, it doesn't show any IMAGES...  Even though there ARE images there - they can be viewed from the media section of the dashboard, just not via the blog post section...
I've also tried it with the original code on line 66 of /Pulsecore/logic/featured_image.php - so it's not my workaround that is affecting that on mine...  I've just checked my permissions and they're all correct..  so perhaps @GRMacGeek 's issue isn't permissions related after all..  

This is what I get when viewing a sub folder when adding blog featured image... Note that inserting an image into the blog post itself DOES work and shows the images..  this screenshot is from using the META section to add blog featured image...

<img width="2560" alt="Screenshot 2019-10-10 at 09 36 18" src="https://user-images.githubusercontent.com/10468020/66553713-864c6300-eb43-11e9-83a5-0024baa4aff7.png">

**Comment by junction10** [comment]
This is the same folder, when inserting an image into the blog post rather than trying to choose one as a blog featured image...  (The first icon showing a broken image is a PDF document, not a JPG or PNG..)

<img width="2560" alt="Screenshot 2019-10-10 at 09 55 50" src="https://user-images.githubusercontent.com/10468020/66554078-3326e000-eb44-11e9-90f3-45b5c635fc2a.png">

**Comment by ghost** [comment]
OK this needs looking into in more detail, thanks for the reports

**Comment by ghost** [comment]
This has been fixed for 5.3.8!
Thanks for the reports
