### ISSUE TITLE
Blog "tags" and "Recent Posts" adding extra "title" in URL link 

### ISSUE THREAD

**Issue by GRMacGeek** [yuzoolcode/pulsecms-tracking#114]
Okay, I upgraded one of my Rapidweaver sites to Pulse 5.3.5, and now Blog tags and "Recent Posts" don't point to the right URL's anymore.

Go here [https://www.ledford-law.com/in-the-news/](https://www.ledford-law.com/in-the-news/) 

Scroll down on the right hand side, and if you click any of the "Recent Posts" links or "Blog Tags" - they are pointing to the wrong URL...

- Every one of the URL's are adding /filename to the end of the URL, which is causing the site to go to a 404 page (in this case I don't have one, so I have it set to go to the Home page...)

These links worked previous to the update (It was on Pulse 5.3.2)

**Comment by GRMacGeek** [comment]
One other observation - I tested this with Pulse 5.3.5 on a "Blocs" site I have.

- The "Recent Posts" tags work - link properly
- But the "Blog Tags" `{{blog-tags:blog}}` don't work

**Comment by jrondorf** [comment]
Please test with following test version of the stacks: https://d.pr/free/f/osiIni

**Comment by jrondorf** [comment]
Test version supplied via direct message in forum.

**Comment by GRMacGeek** [comment]
Okay - new test version of Pulse Integration Stack fixes "Recent posts" issue, thanks @jrondorf !

- But "Blog tags" are broken in Pulse "vanilla" doesn't work anywhere... Michael?

**Comment by ghost** [comment]
- `{{blog-tags:blog}}` fixed in 5.3.6
- blog tag filtering fixed also

Has that fixed it for you @GRMacGeek ?

Thanks 🙏
