### ISSUE TITLE
{forms} fields use standard language from Pulse admin settings

### ISSUE THREAD

**Issue by MarcTWeber** [yuzoolcode/pulsecms-tracking#115]
When I use the Localizer content for forms, all fields get translated correctly to currenty from the user selected language (e.g. German for DE) except the "Send" Button text and some error messages (e.g. Please fill out field xxx)/comments/hints for the form. How can those be change dynamically using the localizer / sb_localizer functionality?

**Comment by ghost** [comment]
We will check and fix this :)

**Comment by ghost** [comment]
Done a quick test without localizer....

To make those work, switch the admin into German:

![CleanShot 2019-09-29 at 20 29 20](https://user-images.githubusercontent.com/4608547/65831722-109cf780-e2f8-11e9-9a0d-a3579cf6f4f3.jpg)
![CleanShot 2019-09-29 at 20 29 56](https://user-images.githubusercontent.com/4608547/65831724-109cf780-e2f8-11e9-917a-00c5e6b946fa.jpg)

**Comment by MarcTWeber** [comment]
Thats what i expected. The site is dynamical changing the language locale=de or en in the menu. This doesn’t work with those texts.

BR Marc

____________________________________________________________________________________________________________
Marc Weber | m.weber@coalignit.com | +49 171 7422765 | +49 6252 7919181

CO•ALIGN•IT | Marc Weber Consulting |  Am Alten Neckar 23 | 64646 Heppenheim | Germany
www.coalignit.com

Am 29.09.2019 um 13:31 schrieb yuzoolcode <notifications@github.com>:

Done a quick test without localizer....

To make those work, switch the admin into German:

**Comment by ghost** [comment]
Now I understand , thank you 

At the moment the Localizer doesn't change the text in the forms, it's only from the settings.
We'll look at this for a future update

**Comment by ghost** [comment]
This is fixed and will be in 5.3.8 

There are some new translations in the language files for {{form}} tag on multi-lingual sites, including reCAPTCHA. The translations are used for the form labels if the user has not changed them in the admin settings. 

Was also referenced on the forum: https://forum.pulsecms.com/t/how-can-i-add-fields-in-the-form/1611
