### ISSUE TITLE
Tag Descriptions erased during update...

### ISSUE THREAD

**Issue by junction10** [yuzoolcode/pulsecms-tracking#117]
Not sure if this is fixed as of 5.3.7, with tag descriptions being moved to main settings page, but every previous update, including from 5.3.6 has wiped the blog tag description settings from the config.json file...

**Comment by ghost** [comment]
This is fixed from 5.3.8 also!

**Comment by junction10** [comment]
Just updated from 5.3.8 to 5.3.9 and the tags and descriptions have been wiped from the /pulse/pulsecore/storage/config.json file again....
