### ISSUE TITLE
Blog post 'Featured Image' (Teaser Image) wrong URL - Workaround/fix?

### ISSUE THREAD

**Issue by junction10** [yuzoolcode/pulsecms-tracking#118]
In 5.3.6 and 5.3.7 - when adding a 'featured image' editing the Meta data in a new blog post, the resulting blog post on the live site has an extra /pulse/ in the URL.. so the img src looks like

/pulse/pulse/content/media/imagename.jpg

and results in a broken image icon, instead of the expected image.

The problem appears to be on line 66 of /pulse/pulsecore/logic/featured_image.php:

`$result->url = \pulsecore\get_configs()->base_url_prefix . \pulsecore\wedge\config\get_json_configs()->json->path . "/{$blog_item->meta_featured_image}";`

I've fixed it, I think, by removing the middle portion, so the code now reads:

`$result->url = \pulsecore\get_configs()->base_url_prefix . "/{$blog_item->meta_featured_image}";`

Hopefully that doesn't break anything else.. the image selector still works when editing the META tags in blogs anyway...

**Comment by ghost** [comment]
Seems to be related to this?
https://forum.pulsecms.com/t/blog-featured-image-media-selector/1676/2

**Comment by ghost** [comment]
And here:
https://forum.pulsecms.com/t/5-3-6-blog-featured-image-wrong-url-solution/1661

**Comment by junction10** [comment]
> And here:
> https://forum.pulsecms.com/t/5-3-6-blog-featured-image-wrong-url-solution/1661

Yes - I posted it there so anyone else could try it if they have the same issue, but reported it here officially as a bug with possible fix.

**Comment by ghost** [comment]
This has been fixed and will be in 5.3.8 release!
