### ISSUE TITLE
Blog is still broken in 5.3.7

### ISSUE THREAD

**Issue by jdloudon** [yuzoolcode/pulsecms-tracking#119]
Hi, still have big issue with blog broken. II have copied an entire client site from here:
https://howtospeakchild.com/

to here:

https://mazy.online/

Note that onthe proper site if you click on the title of a blog post it opens up in its own page.
With the test site it just reloads the blog page.
Likewise on the Interview page which is a sub blog and is actually displaying again now ( it wasnt in 5.3.5) click on a title and you just get taken back to main blog page.
Also {{social}} not working
I think more people are using Pulse for Blog than Ecommerce so please get this looked at.
Thanks

**Comment by pcalej** [comment]
Hello @jdloudon, the blogs seem to be working perfectly on our test server and localhosts. Will you be able to do a fresh install and send us the logs so that we can look into it?

Thanks!

**Comment by ghost** [comment]
Also @jdloudon can you confirm the base URL and .htaccess are set correctly, thanks

**Comment by ghost** [comment]
If you are able to send us the logs then please drop by and chat with us on the site. Until then will close this as not able to replicate the errors

**Comment by jdloudon** [comment]
Thanks for getting back to me on this. I have reinstalled and it seems to
be okay now.
Cheers
