### ISSUE TITLE
Settings page broken - 5.0.2

### ISSUE THREAD

**Issue by jetwes** [yuzoolcode/pulsecms-tracking#12]
The setting page is broken on a fresh download (downloaded just now) of Pulse 5.0.2.
The Dashboard is working - but the settings page not.
![image](https://user-images.githubusercontent.com/1346373/35766184-42135d6e-08d3-11e8-9cd4-5c849bfc9273.png)

**Comment by ghost** [comment]
- is that local?
- if remote, any URL?
- did you /admin/install.php?

**Comment by jetwes** [comment]
url : http://zph.star-media.biz/
i did run the install scrip /admin/install.php

**Comment by jetwes** [comment]
js console is reporting couple of errros - all related to strict MIME type:

`Refused to execute script from 'http://zph.star-media.biz/admin/admin/js/jquery.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`

**Comment by jetwes** [comment]
same on frontend - menu isn't working 
js-console: 
`(index):1 Refused to execute script from 'http://zph.star-media.biz/admin/inc/tracker.php?uri=/&ref=none' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`

**Comment by jetwes** [comment]
http://zph.star-media.biz/reqs.php

**Comment by jetwes** [comment]
i think this is nginx related... just added the location options you specified for nginx in your troubleshooting guide - then i get:
Undefined property: stdClass::$url_prefix in /home/forge/zph.star-media.biz/public/pulsecore/dispatcher.php on line 19

maybe your nginx rec. are outdated?

**Comment by ghost** [comment]
Sure - we need to look at that. 99% of Pulse users are using Apache and shared hosting.
We'll need to test again in Nginx

**Comment by jetwes** [comment]
ok - i can't get it to work..
here my actual nginx config for location:
`location / 
    { 
        index index.php;  

        rewrite ^/tagged\/(.*)$ /?p=blog&blog_tag_name=$1 last;
        rewrite ^/blog-page-([^-]*)$ /?page=$1&p=blog last; 
        rewrite ^/blog-([^-]*)+? /?d=$1&p=blog last;  
        rewrite ^/endpoint\/(.*)$ /end_point.php?item=$1 last;
        rewrite ^/dropzone_upload_handler.php$ /dropzone_upload_handler.php last;
        
       if (!-f $request_filename){
	        set $rule_5 1$rule_5;
        }
        if (!-d $request_filename){
	        set $rule_5 2$rule_5;
        }
        if ($rule_5 = "21"){
	        rewrite ^/(.*)$ /index.php?p=$1 last;
        }
    }`
the setting page is working now - i had 
add_header X-Content-Type-Options "nosniff"; in my config - that seems to be a problem for pulse...

now in frontend menu is missing, blog is showing:
`Fatal error: Uncaught LogicException: An invariant has failed in /home/forge/zph.star-media.biz/public/pulsecore/dbc.php:12 Stack trace: #0 /home/forge/zph.star-media.biz/public/inc/tags/blog.php(40): pulsecore\invariant(false) #1 /home/forge/zph.star-media.biz/public/index.php(288): include('/home/forge/zph...') #2 {main} thrown in /home/forge/zph.star-media.biz/public/pulsecore/dbc.php on line 12`

seems both rewrite relating for nginx

**Comment by ghost** [comment]
Thanks - will update on this soon - will setup Nginx testing environment

**Comment by jetwes** [comment]
maybe there's another general problem with 5.0.2 - same errors appear on #22 #19 
not nginx related

**Comment by ghost** [comment]
#22 + #19 will be fixed in an update today

Re: Nginx

On the nginx config: did some testing and the current one still works http://help.pulsecms.com/article/9-troubleshooting-installation

Not sure what you're doing wrong...

- Please try again with fresh 5.0.3 install (when released today)
- then apply Nginx config: http://help.pulsecms.com/article/9-troubleshooting-installation

**Comment by ghost** [comment]
Closing as ran Nginx tests and can't replicate.
The current one still works http://help.pulsecms.com/article/9-troubleshooting-installation

Try Pulse 5.0.3 and notify us if you still can't get this working 👍

**Comment by jetwes** [comment]
Most errors were pulse 5.0.2 related. I have one issue - opening another ticket for it.
