### ISSUE TITLE
{{sb_login}} not working after 5.3.7 update

### ISSUE THREAD

**Issue by modularev** [yuzoolcode/pulsecms-tracking#123]
After the update the login functionality is gone and the page is accessible without any password. I'm using Pulse with Blocs

**Comment by ghost** [comment]
This has been tested in 5.3.7 and is working. 

- Can we have some more information? 
- Are you using the command {{sb_login:password}}?
- Did the update work successfully?
- Are there any bug reports under the settings and debug setting?

thanks

**Comment by ghost** [comment]
I can confirm this is working...

1. Page added with Lock Tag:

![CleanShot 2019-11-12 at 13 48 33](https://user-images.githubusercontent.com/4608547/68643018-436f1800-0553-11ea-9bc0-71a17296b25b.jpg)
`{{sb_login:cheese}}`

2. Greeted with login screen
![CleanShot 2019-11-12 at 13 48 54](https://user-images.githubusercontent.com/4608547/68643043-5681e800-0553-11ea-92a3-d20f7f02d91c.jpg)

3. Type in "cheese" and get access:
![CleanShot 2019-11-12 at 13 48 19](https://user-images.githubusercontent.com/4608547/68643052-5da8f600-0553-11ea-943b-d8a135dd24fb.jpg)

Please check it again and supply us with any error logs
Also make sure you are not logged in as Admin as you will be able to see the page contents
