### ISSUE TITLE
Missing Feature - "Highlighted Text" in preview mode is lost when in html mode is toggled. Missing since v5.3.3

### ISSUE THREAD

**Issue by AceTutor** [yuzoolcode/pulsecms-tracking#124]
I hope I have described the issue correctly and that it is repeatable elsewhere!
Further to my missing "**Control S**" feature I have also realized that highlighting text in either **html** view or in **normal** view is lost when you toggle the html button. This is an incredible feature in training new clients not familiar with html, tags, css, etc.

_Here are screen shots from vs5.3.3._ 
![image](https://user-images.githubusercontent.com/593990/66779315-240fab80-ef11-11e9-8f5c-6c0e95485b4b.png)
![image](https://user-images.githubusercontent.com/593990/66779397-6afda100-ef11-11e9-8474-990615e5b063.png)

**Comment by pcalej** [comment]
Hello @AceTutor, thanks for pointing that out! This is indeed a really handy feature to have. We'll take this into account and look into the possibility of bringing it back in our future updates.

**Comment by ghost** [comment]
Sorry about this @AceTutor 
This is useful but I think this must have been changed in Redactor 3.2.0 

You can see in their online demo it's the same:
https://imperavi.com/redactor/examples/initialization/base-example/

We've asked them to bring it back but for now I'm afraid it's gone and it's an initialisation we can bring back on :(

**Comment by AceTutor** [comment]
> We've asked them to bring it back but for now I'm afraid it's gone and it's an initialisation we can bring back on :(

I think you mean **can't** bring back on!
Thank you for asking for it to be reintroduced. Hopefully real soon!

**Comment by AceTutor** [comment]
Thanks for release 5.3.10. All's going good with its install and usage thus far is flawless.
I notice as part of this update that you have now updated Redactor to vs. 3.3.3.

**I would like to know if the missing "Highlighted Text" feature that we agreed was valuable to Pulse has been re-requested with Imperavi?** 

Somehow I believe the Pulse Team or Imperavi, if not prompted seem to push things aside to the too hard basket through their lack of seeing a feature benefits - yet it is important to me and my customers! Please don't "close" this request with haste.

I look forward to seeing if you can again seek a better answer to this quest!

Kind regards
AceTutor
