### ISSUE TITLE
Dropzone tag icon missing

### ISSUE THREAD

**Issue by GRMacGeek** [yuzoolcode/pulsecms-tracking#125]
When I use the "Dropzone tag" `{{dropzone:media/gallery1}}` a piece of "code" appears in the box `</form>` where I think a button or something should be...

test page here [https://www.grmacgeek.com/best/shane](https://www.grmacgeek.com/best/shane)

- Also, is there a way to add pdf's as an "allowed" file type in Dropzone?

See attached pic as well
![dropzone](https://user-images.githubusercontent.com/6706155/66820366-86b37800-ef0e-11e9-9c21-995facce0ebb.png)

**Comment by GRMacGeek** [comment]
Figured out where the conflict was:

- I had added an "embed with design code" from "Just Forms"
- This created that `</form>`  in the Dropzone box
- If I remove that embed code, the issue goes away

However:

- The Dropzone icon is missing... just an "empty box"
- I would still like to know how to change the Dropzone settings to allow pdf's though

**Comment by ghost** [comment]
Regarding the icon @GRMacGeek - it seems to be working in the default theme:

![2019-10-27 at 10 00](https://user-images.githubusercontent.com/4608547/67632191-bcf2df00-f8a0-11e9-8a85-a18f85d436bf.jpg)

- were you connected to the internet? I guess so - it references FA5
- was it a different theme?

I'm guessing the template wasn't using FA5 so we need to either reference that in the core or add it to your page temporarily

**Comment by ghost** [comment]
- have made an adjustment so this will appear for sure in all situations in the next update (5.3.8)
