### ISSUE TITLE
form blocks

### ISSUE THREAD

**Issue by ManuelRosique** [yuzoolcode/pulsecms-tracking#126]
Hello, I am having a problem with the form of a new site that I am implementing with blocsapp and pulsecms, when sending the form, the error message appears, provide the form without pulsecms and it works correctly, when using it with pulsecms mark error, they will have a idea what could it be?

**Comment by ghost** [comment]
- Can you provide more information?
- Are you using the {{form}} tag?
- Are you trying to use a Form from Blocs?
- Do you have the error?

**Comment by ManuelRosique** [comment]
I am using pulsecms 5.1, just check that the email cannot be sent.

It is a form of Blocsapp.

**Comment by ghost** [comment]
Pulse 5.3.7 is definitely working with forms so it might have been an update since then.

Can you try:
- another email address
- smtp settings
- check the junk mailbox
- forms from Blocsapp shouldn't be mis-aligning with Pulse forms as it's a different code integration

**Comment by ManuelRosique** [comment]
I already tried everything, on your list but nothing, just still appears wrong when sending.

I uploaded the site in normal html of blocsapp and it works great.

I don't know if it has to do with the new version of blocsapp, but it worked before ...

Could you send me the latest version download link that came out in August?

**Comment by ghost** [comment]
We'll do more testing with the latest Blocs app and if there's a bug will issue a fix.

To download the latest or past versions you need to access your Pulse account dashboard:
https://pulsecms.com/dashboard.php

**Comment by ghost** [comment]
If forms are added the Pulse way 
eg
`{{form}}`
Then it works

To do this:
- create an HTML Bric in Blocs app where you want the the form to appear.
- then after exporting as a Pulse5 template and adding the contents to the server, go to the above Block
- In my demo Blocs app labelled it as Myblock-38504
- Go in there and paste the form tag
- Make sure to add the recipient in the Pulse Admin settings under "Form"
- If it fails please check the logs and let us know
- Please check the SPAM
- Or use the SMTP settings
- It is certainly working as a Form either in Pulse or in Pulse+Blocs

![CleanShot 2019-11-12 at 14 20 34](https://user-images.githubusercontent.com/4608547/68644343-0a857200-0558-11ea-8e97-77163d72d51c.jpg)
