### ISSUE TITLE
{{recentposts_visual:"3"}} not showing up in the latest version

### ISSUE THREAD

**Issue by pcalej** [yuzoolcode/pulsecms-tracking#127]
as described

**Comment by Arties-be** [comment]
Urgent fix needed. Site is about to go live and has to be delayed again. Angry client as a result. Willing to get somebody from Pulse CMS team on board to have a look at it. 

Thank you.

**Comment by ghost** [comment]
Seems to be working:

<img width="1119" alt="Screenshot 2019-10-25 at 12 32 07" src="https://user-images.githubusercontent.com/4608547/67564572-86438a00-f723-11e9-9d16-05277179e260.png">
<img width="1119" alt="Screenshot 2019-10-25 at 12 32 17" src="https://user-images.githubusercontent.com/4608547/67564574-86438a00-f723-11e9-9cee-9b8ce642af7f.png">

Do you have anymore information that will help us test?
- Can you share any bug reports from the site?
- Are you using the tag on a Page or Block? Both work in our testing...

**Comment by ghost** [comment]
Looking at your supplied image... I think your " is not " it is Curly
Please be sure it is not curly quotes...
https://chrisbracco.com/curly-quotes/

**Comment by Arties-be** [comment]
> Looking at your supplied image... I think your " is not " it is Curly
> Please be sure it is not curly quotes...
> https://chrisbracco.com/curly-quotes/

THNX! Thats it but now i have other problems. :)

My templates just got messsed up without me changing anything. No idea why this keeps happening. I'm checking my workflow now. So weird; I used straight " at the first design so it changed to the other one at some point. 

Anyway Thank you for pointing that out. It works!

**Comment by pcalej** [comment]
@Arties-be, are you using a custom template?

**Comment by ghost** [comment]
@Arties-be As mentioned in that link it's a Mac that switches it on so you need to ensure it is off 
https://www.iclarified.com/38772/how-to-disable-curly-quotes-in-mac-os-x-mavericks

Changes with OS updates sometimes..
