### ISSUE TITLE
Upload of PDF files - Not showing the files in de cms

### ISSUE THREAD

**Issue by Arties-be** [yuzoolcode/pulsecms-tracking#128]
After uploading files in the media part inside a fresh folder. 
I get a succes message but no files are visible in de CMS. 
I've checked with FTP if the files got uploaden and they are uploaded on the server just not visible in the manager. (Upgraded from 5.3.2 to the latest version a day ago )

**Comment by ghost** [comment]
We've made a fix to this and it will appear in 5.3.8!
