### ISSUE TITLE
Pagination not working in Blogs

### ISSUE THREAD

**Issue by GRMacGeek** [yuzoolcode/pulsecms-tracking#13]
When I click the pagination links on a blog page, goes to error page

- Using Pulse 5.02 and Rapidweaver Integration
- Link to [website here](https://www.servicemastergrandrapids.com/tips/)
![servicemaster_grand_rapids_tips_and_latest_news](https://user-images.githubusercontent.com/6706155/35773025-a0508b86-0914-11e8-8ae7-5f39f94b1e9e.jpg)

**Comment by jrondorf** [comment]
For me, it looks like you still are using pulse and RW project not in root. That is not supported. 

https://www.servicemastergrandrapids.com/~servicemastergr1/pulse/tagged/Fire+Damage

**Comment by jrondorf** [comment]
Related to #16
