### ISSUE TITLE
broken link in media subfolder galeries pulse 5.3.7

### ISSUE THREAD

**Issue by annett-g** [yuzoolcode/pulsecms-tracking#130]
Hi, I have again in Media folder, in another folder and pictures. The gallery tag ({gal: afrika / animals}) to insert is correct, but the images are not displayed on the page. The folder link is missing.
media / afrika / animals / hippo.jpg is not working.
the image has the following link: https: //localhost//customer/content/media/animals/hippo.jpg
The first folder "afrika" is missing.
Can someone please check that?
Thank you - Annett # #

**Comment by ghost** [comment]
Thanks @annett-g for the report - we'll take a look and get this in the next update

**Comment by ghost** [comment]
This has been solved @annett-g and will be in the 5.3.8 release - thanks for reporting it.

This was an interesting bug. When there was no gallery.txt the import was generating the correct data. The gallery.txt file was chopping up the relative directory. This should be fixed now and handling sub-sub folders properly also. 

Sorry about that !

**Comment by annett-g** [comment]
Oh, you do not have to apologize! Pulse is great and mistakes happen.
I'm glad it works again.
