### ISSUE TITLE
Pulse logo header URL problem

### ISSUE THREAD

**Issue by pcalej** [yuzoolcode/pulsecms-tracking#132]
url shows admin//index.php instead of admin/index.php

redirects to admin page but as soon as anything is saved, it crashes out to the login screen and loses all .css ( a white screen with just the login box)

![image](https://user-images.githubusercontent.com/56381431/68760761-9200dd00-064d-11ea-91b8-a6ccd38f02ee.png)
![image](https://user-images.githubusercontent.com/56381431/68761118-5b779200-064e-11ea-82e8-71820786ee20.png)

**Comment by ghost** [comment]
Fixed in 5.3.8!
