### ISSUE TITLE
Special characters in blog and media

### ISSUE THREAD

**Issue by annett-g** [yuzoolcode/pulsecms-tracking#133]
Good morning Michael, unfortunately I still have problems with the umlauts. We in the German-speaking countries often use äöü, unfortunately Pulse removes them in the blog-url. Unfortunately, I can not say if the link works, because blog links do not work in version 3.5.7. 
![Umlauts-Blog](https://user-images.githubusercontent.com/57502641/68836602-04f46d00-06bb-11ea-93c8-812ddc35c549.png)
I took a screenshot. Maybe you can look again.
Umlauts in navigation work perfectly!
Thank you very much
Annett

**Comment by ghost** [comment]
Thanks ... we'll test this for 5.3.9!

**Comment by ghost** [comment]
Just to check.. do you usually have äöü in the URLs in German?
Thanks

**Comment by ghost** [comment]
Ref:
https://stackoverflow.com/questions/43661556/how-to-change-german-umlauts-to-get-friendly-url

> The function can be tested here : http://tests.brillault.fr/fonctions/string_to_url.php, it converts my-word-äöß to my-word-aoss.

**Comment by annett-g** [comment]
Yes, there are also umlaut domains for the .de domains. Here is a simple explanation - unfortunately you have to translate it:
https://www.checkdomain.de/blog/domains-hosting/umlautdomains-clevere-alternative-oder-ein-problem/
I do not know if that's a problem.
My problem here was the special characters in the blog URL. I mean, in an earlier version of Pulse, that worked very well, so I think it can be fixed? 
Alternatively, internationally, Pulse could swap the umlauts in the URL -> ä = ae, ... The customer himself will not pay attention to this because these special characters are very common in our language and are part of the keyboard. But yes, that would be a good solution!
Thank you so much!
Annett

**Comment by ghost** [comment]
Thanks @annett-g 

This is fixed for the next version.

As part of this the blog-id and f_param filters were updated to handle UTF8 letters. This does have the side effect of mangled filenames if the underlying filesystem does not support UTF8 or uses something else like UTF16.
