### ISSUE TITLE
Updating from settings

### ISSUE THREAD

**Issue by pcalej** [yuzoolcode/pulsecms-tracking#134]
Updating from settings redirects to a blank page on localhost
5.3.7 > 5.3.8
![image](https://user-images.githubusercontent.com/56381431/69110624-423f6d00-0ab6-11ea-815f-bf7a96e71c9b.png)

5.3.6 > 5.3.7 redirects to a totally blank white page

**Comment by ghost** [comment]
Added some error trapping when uploading Pulse core updates that exceed the server upload limit. 

This happens when the upload is larger than the POST MAX SIZE limit. So uncommenting that in the .htaccess fixes this.

This is ready for 5.3.9

**Comment by ghost** [comment]
Extra note: This only happens for some users and if a user has their php.ini settings for post max filesize/ post max size less than the update zip file size.
