### ISSUE TITLE
block-loop no longer works in 3.5.8

### ISSUE THREAD

**Issue by annett-g** [yuzoolcode/pulsecms-tracking#135]
I tried all sorts of variations, with and without "", does not work anymore.
![Screenshot_2019-11-20 Block-loop](https://user-images.githubusercontent.com/57502641/69222827-8ac05e80-0b7a-11ea-84c0-9dd696814157.png)

**Comment by ghost** [comment]
Thanks @annett-g for reporting this

This is out in 5.3.9:
- Added support for percentage % characters in attribute strings

But the fix in the meantime is:
File:  pulsecore/src/tag/lexer/token/tag_attribute.php

Change L12 to:
`protected $re = "/^(\:[\w\"\/'\-\(\)\<\>\[\] @\.\#=,\ \p{Sc}&;\%]+)/u";`

**Comment by annett-g** [comment]
Thank you, works perfectly!
