### ISSUE TITLE
Server error 500 (redirection) with editor login (3.5.8)

### ISSUE THREAD

**Issue by annett-g** [yuzoolcode/pulsecms-tracking#136]
I have set up an editor LogIn for my client - as far as everything works. If I log out, however, there is a server error 500 in the frontend.
It is not enough if I login as an administrator, even after this logout there is the server error
It is also not enough to remove the editor and everything in the admin backend.
Only after I removed the entire section in the config.json does the page work again.
This error already existed in the previous version 3.5.7
I've attached the section I deleted once as a file - hope it helps with troubleshooting.
[Editoren.pdf](https://github.com/yuzoolcode/pulsecms-tracking/files/3902700/Editoren.pdf)

**Comment by ghost** [comment]
Hi @annett-g 

We've made a fix for the logout redirect by making sure the full path + domain are used. I'm not sure that fixes your issue though. I think a look at the error log is needed. 
Please can you attach it?

Thanks

**Comment by ghost** [comment]
We can't replicate this. We suspect there might be some kind of interaction between the hardwired editor user and a new user. 

We tried adding an editor user and still couldn't replicate. 

So we'd be most grateful from more info on how to replicate this!
Thanks

**Comment by ghost** [comment]
Closing this for now and let's re-test after 5.3.9 released shortly...
