### ISSUE TITLE
Problem with .htaccess PulseCMS version 5.3.9

### ISSUE THREAD

**Issue by bigbossie** [yuzoolcode/pulsecms-tracking#137]
When I copy the PulseCMS 5.3.9 file to the host server and then do the install with [websitename]/admin/install.php I get the notification that "This page is not working", {website} has redirected too many times, try to delete your cookies, ERR_TOO_MANY_REDIRECTS. Whatever I try, delete my cookies , nothing works. The message keeps the same. 
I made a ticket to my hostprovider and they came back that the lines"
==
# ensure HTTPS - comment out lines 10 and 11 if installing locally without an SSL certificate
RewriteCond %{HTTPS} off
RewriteRule ^/?(.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
==
are not necessary, because the forcing of HTTPS is already done by there system of the Hosting Provider.

The .htaccess file contains:
======
# Uncomment line 2 and 3 below if uploading issues via Media or Dropzone
# php_value upload_max_filesize 20M
# php_value post_max_size 25M

RewriteEngine On

RewriteBase /

# ensure HTTPS - comment out lines 10 and 11 if installing locally without an SSL certificate
RewriteCond %{HTTPS} off
RewriteRule ^/?(.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

# draft blog pages
RewriteRule ^blog-draft-([^-]*)? "index.php?p=blog-draft-$1" [L,QSA]

RewriteRule ^tagged\/(.*)$ ?p=blog&blog_tag_name=$1 [L,QSA]

RewriteRule ^blog-page-([^-]*)$ ?page=$1&p=blog [L,QSA]
RewriteRule ^blog-([^-]*)+? ?d=$1&p=blog [L,QSA]

# end points for embedding into non-Pulse sites
RewriteRule ^endpoint\/(.*)$ end_point.php?item=$1 [L,QSA]

# drop zone upload handler
RewriteRule ^dropzone_upload_handler.php$ dropzone_upload_handler.php [L,QSA]

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d 
RewriteRule ^(.*)$ index.php?p=$1 [QSA,L]

# Adds SVG image support
AddType image/svg+xml svg svgz
AddEncoding gzip svgz

# add audio/video support
AddType video/mpg .mpg
AddType video/ogg .ogv
AddType video/mp4 .mp4
AddType video/webm .webm

AddType audio/mpeg .mp3
AddType audio/ogg .ogg
AddType audio/mp4 .m4a
AddType audio/wav .wav 

# block directory listing
Options -Indexes
======
After deleting the "# ensure HTTPS..................................", I get the error message HTTP ERROR 500.

What is wrong here? Do I something wrong? I only have copied the PulseCMS files to the server and I can't install it because of this. Please help?

With Regards,

Jeroen Kotterlink

**Comment by ghost** [comment]
Thanks, you can delete lines 10 and 11

But does your host provide an SSL certificate?

**Comment by ghost** [comment]
![CleanShot 2020-01-18 at 10 52 11](https://user-images.githubusercontent.com/4608547/72656714-a0b69800-39e0-11ea-9bd1-93665a1b248c.jpg)

For example on localhost I don't have SSL installed and uncommented those lines added a "#" and ran the installer and it worked fine

If you are getting a HTTP ERROR 500 then something else is wrong on the server

- What server is it?
- what version of PHP?
- run the test on it and see if compatible: https://www.pulsecms.com/resources/reqs.zip

**Comment by bigbossie** [comment]
Hello,

I deleted the lines 10, 11 and SSL certificate is installed. I ran the test and everything seems OK. (See printscreen)

I don't know what I can do now.
Is there specific information I need from my provider why this isn't working?
With regards, Jeroen

![reqs](https://user-images.githubusercontent.com/5787019/72683341-d342bc80-3ad6-11ea-9701-d899dde2c4dc.jpg)

**Comment by ghost** [comment]
- can you share a link?
- where are you hosting (what provider?)
- what are they saying about the site?

**Comment by ghost** [comment]
Reference:
https://forum.pulsecms.com/t/problem-with-pulsecms-5-3-9-err-too-many-redirects/1791

**Comment by bigbossie** [comment]
Hello,

The link to the site I have troubles with is https://pulse.bigbossie.nl <https://pulse.bigbossie.nl/> 
The hosting provider is mijndomein.nl <http://mijndomein.nl/>
They are saying that the lines 10 and 11 are not needed because their system is doing that and the http error 500 is something I had to find out with you because this error is not logged and has to do with the pulse software. Thats what they say.


Met vriendelijke groet, with regards, 

Jeroen Kotterlink
jeroen@bigbossie.nl

**Comment by ghost** [comment]
Thanks 

Seems we are talking here also:
https://forum.pulsecms.com/t/problem-with-pulsecms-5-3-9-err-too-many-redirects/1791/10

Can you attach your site logs?
(go to Debug from Admin drop down and upload them to here or the forum post)

Thanks

**Comment by bigbossie** [comment]
Hereby the log files from the site/server.


[Archive logs.zip](https://github.com/yuzoolcode/pulsecms-tracking/files/4128080/Archive.logs.zip)

**Comment by ghost** [comment]
These are the general web server logs and not the pulsecms ones. 

Can you get the logs from the pulse admin under settings and "debug" or from the server Pulse install under pulsecore/storage/logs

Thanks

**Comment by bigbossie** [comment]
Hereby I send you the logfiles from the server pulse core/storage/logs.




Met vriendelijke groet, with regards,

**Comment by bigbossie** [comment]
Hello,

Why is this closed? The problem still exists! Why does it take so long to answer and give or find a solution? Is this the support I can expect for this product?
Please answer me in a short time!!!!!

with regards,

**Comment by ghost** [comment]
Thanks for getting back in touch

* We've been emailing you many times over the past 2 weeks asking for the logs but haven't heard back, can you check your email spam/junk filter and please reply?

* The logs attachment might have been too big so please send as a Gdrive or Dropbox as we haven't received anything from you. Please note that these are GitHub notifications and nothing was attached.

* 5.3.10 has been released today and may fix your issue

* We can't replicate what you've done so need more information :(

**Comment by bigbossie** [comment]
Hello,

I sent everything in through the github. The new version still gives the same error about too many redirects. Therefore, the issue isn’t close as you mentioned earlier in a mail before. Can you update me about the time that this will take to solve?
I’m almost out of usage of pulse about 4-5 months. My license is until somewhere in march.







Met vriendelijke groet, with regards, 

Jeroen Kotterlink
jeroen@bigbossie.nl
Mbl: +31 6 38332295
