### ISSUE TITLE
Tags & Descriptions issue not fixed..

### ISSUE THREAD

**Issue by junction10** [yuzoolcode/pulsecms-tracking#138]
https://github.com/yuzoolcode/pulsecms-tracking/issues/117

This issue still exists - just updated from 5.3.8 to 5.3.9 and it wiped all the existing blog tags and descriptions from the config.json file.

***Edit*** :  Issue occurred on local test server running Mamp Pro with PHP 7.3.8
Just backed up the config file just in case, and updated the actual live site, and it's correctly retained the tags..  no idea why the local server didn't?

**Comment by ghost** [comment]
Yes this is strange and can't replicate. 

If the live site has worked for you that's great. There might be a difference between the PHP on the live site and the localhost. Not sure. will need to keep an eye on this and you did the right thing to backup before updating anyway.

Thanks for the report.

**Comment by ghost** [comment]
Seems ok for now and can't replicate but if still persists in 5.3.10 then will need looking at again!
