### ISSUE TITLE
Problems with sb_login

### ISSUE THREAD

**Issue by annett-g** [yuzoolcode/pulsecms-tracking#139]
I have problems with sb_login, inserted in Pages.
If I enter my tag as in the manual, the tag is shown on the page - without parsing.
I don't need an OTP password, so I'll leave it blank.
{{sb_login: demo :: folder / blockname: incorrect entry}}
looks like:
![sb_login-1](https://user-images.githubusercontent.com/57502641/72608082-363f2280-3922-11ea-9350-2b5c2f34b1c9.jpg)

If I remove the **:** , the login is displayed, but I should enter an OTP, which I don't want or can't do.
{{sb_login: demo: folder / blockname: incorrect entry}}
![sb_login-2](https://user-images.githubusercontent.com/57502641/72608109-46570200-3922-11ea-83ab-42b168e0cf42.jpg)

Is there a simple solution for that?
Thanks a lot!
Annett

**Comment by ghost** [comment]
https://youtu.be/FXTprWh59Hw?t=211

I added a lock login in the video at that point above..
If this is not working will need more testing!

**Comment by ghost** [comment]
Just did a test @annett-g and it seemed to work

I used:

`{{sb_login:lemons}}`

![CleanShot 2020-01-18 at 10 58 30](https://user-images.githubusercontent.com/4608547/72656878-b8425080-39e1-11ea-8520-f5ef3cba94a6.jpg)


![CleanShot 2020-01-18 at 10 59 16](https://user-images.githubusercontent.com/4608547/72656880-bd070480-39e1-11ea-99e5-baaaccb71e7b.jpg)


![CleanShot 2020-01-18 at 10 59 27](https://user-images.githubusercontent.com/4608547/72656884-c2644f00-39e1-11ea-935c-5741f35e2a78.jpg)

This works to lock the whole page. Let me know if this helps!

**Comment by annett-g** [comment]
Thanks Michael, that works very well and is all I need.
But maybe you can check again if it works again if you only want to encrypt one article (block) in one page. I think we have had it before and it worked just fine.

**Comment by ghost** [comment]
Thanks @annett-g - yes you are right it used to work that way but we had to change it to be page only at some point unfortunately. I hope that is ok for most use cases at the moment.

Thanks!
