### ISSUE TITLE
New navigation question

### ISSUE THREAD

**Issue by annett-g** [yuzoolcode/pulsecms-tracking#140]
So first: the new navigation works great! Perfect with a little practice. ;)
Unfortunately Pulse does not read the 3rd level in the Pages folder, so in my example (pages) Faecher -> Sport.
![grafik](https://user-images.githubusercontent.com/57502641/72669083-07ae6e00-3a2e-11ea-846c-70d8fa49d17f.png)

I can create the sub-menu item, but there are no pages ... 

![grafik](https://user-images.githubusercontent.com/57502641/72669102-47755580-3a2e-11ea-8cee-0bd115c675d3.png)

I think it is **not a bug**, just a matter of order in my data. For large pages, it makes a lot of sense for me to sort the pages into folders in the way they should then be displayed on the page.

Maybe you will get it in a next version, then everything is perfect!
Thank you very much
Annett

**Comment by ghost** [comment]
Looking at this it might actually be a feature request that we'll have to leave open for now and have as something to maybe do in the future.

The pages aren't added automatically to the menu. So this would need to be done manually at the moment. 

Having this done automatically (ie mapping folder levels onto menu items) is something to think about. Not sure how to set it up that won't be surprising to the end user.

**Comment by annett-g** [comment]
Yes, that's not a problem at the moment.

Well, for the user, I think it would be enough if the pages were simply listed like all other pages. On the file path you can see very well that the files are in a folder and then assign them in the menu or submenu.
So, just list them. Users or designers then assign themselves ;)

**Comment by ghost** [comment]
Closing for now as a feature request to bear in mind for a larger update
