### ISSUE TITLE
Manager User Group creates errors -  "Undefined variable:" - vs 5.3.10

### ISSUE THREAD

**Issue by AceTutor** [yuzoolcode/pulsecms-tracking#143]
On a new install on both my local server and live server I have discovered that as soon as the **Manage User Group**  function is run an error message is created in the "error log". Thereafter, every time a page is opened or refreshed that error log is updated with the same error message.

Here is a copy of that error taken from my live server account . . .

> [16-Mar-2020 05:02:47 Asia/Tokyo] PHP Notice:  Undefined variable: param_get_f in /home/fstfield/public_html/demo/pulse/pulsecore/template/admin/open/page.phtml on line 58
[16-Mar-2020 05:14:50 Asia/Tokyo] PHP Notice:  Undefined variable: param_get_f in /home/fstfield/public_html/demo/pulse/pulsecore/template/admin/open/page.phtml on line 58
[16-Mar-2020 05:17:58 Asia/Tokyo] PHP Notice:  Undefined variable: param_get_f in /home/fstfield/public_html/demo/pulse/pulsecore/template/admin/open/page.phtml on line 58

When I view the meta data associated with any page (after creating a Manage Group) I notice on my live server that a normal check box appears related to that Group. When I look at the meta data on my local server install I am seeing the error message displayed in full prior to the check box name. Here is what I see for a group I have chosen to call 'Home' 

> Notice: Undefined variable: param_get_f in E:\1 - All Work\Customers\Fieldsappers\www.1fieldsappers.org\site\www\pulsecore\template\admin\open\page.phtml on line 58
/> Home 

On both installations - as soon as the User Group is removed **all error messaging ceases**.

Live Server: Using PHP 7.2
Local Server: Using PHP 7.2.24
Pulse Version: vs 5.3.10 (current latest)

**=====================================**
**Please note**

_1. I am new to using the "user permissions" feature in Pulse. In the above process I have not gone to the next step of adding a user.
2. I would appreciate if a video could be made or at least a specific help file made to explain the correct workflow of all various feature options of USER Permission's._

 
**=====================================**

**Comment by ghost** [comment]
Thanks John for reporting this - we've logged this and will do some testing for the next release and update you on this workflow

**Comment by AceTutor** [comment]
Hi Michael and the rest of the Pulse cohort!
A month has past and by now I would have thought that testing, problem solving and reporting back aught to have long since happened! Is someone able to update us? 
Tis frustrating to say the least. 
Timely client support is imperative particularly with a subscription based product!
Thanks

**Comment by ghost** [comment]
This has been fixed and will appear in 5.3.11 which is out shortly
