### ISSUE TITLE
Blog tags don't work in Rapidweaver

### ISSUE THREAD

**Issue by GRMacGeek** [yuzoolcode/pulsecms-tracking#15]
If you click a "blog tag" it takes you to a "generic Pulse 5" blog page, complete with generic "Acme" branding... how can this page be edited by Rapidweaver?
[Link to Pulse blog here](https://www.servicemastergrandrapids.com/tips/)
![servicemaster_grand_rapids_tips_and_latest_news](https://user-images.githubusercontent.com/6706155/35773131-2134b7ca-0917-11e8-8d76-9610abc9d4af.jpg)

**Comment by jrondorf** [comment]
Same here...

**Comment by jrondorf** [comment]
I will leave this closed, as it is related to #16
