### ISSUE TITLE
Blog posting in Rapidweaver loses all formatting

### ISSUE THREAD

**Issue by GRMacGeek** [yuzoolcode/pulsecms-tracking#16]
When you "click" into a blog post from the main feed in a Pulse5/Rapidweaver blog, you lose all formatting of the blog post & there are other"icons" and "social" links there...

Link to main page - [https://www.servicemastergrandrapids.com/tips/](https://www.servicemastergrandrapids.com/tips/) and click any blog title...
![servicemaster_grand_rapids_tips_and_latest_news](https://user-images.githubusercontent.com/6706155/35773198-32e9920e-0919-11e8-90cc-05289d8093e2.jpg)
![winter_preparation_tips-clicked](https://user-images.githubusercontent.com/6706155/35773200-3539341a-0919-11e8-8917-595bdd3922da.jpg)

**Comment by jrondorf** [comment]
Same here...

**Comment by GRMacGeek** [comment]
Wrong - it is setup exactly as it is supposed to be, per your instructions...
![sma_-_servicemaster](https://user-images.githubusercontent.com/6706155/35779915-7860b464-09a2-11e8-89c2-0456f093652e.jpg)

**Comment by jrondorf** [comment]
What is then
https://www.servicemastergrandrapids.com/~servicemastergr1/pulse/

~servicemastergr1 ??

**Comment by jrondorf** [comment]
Every link on that page is wrongly generated. Are there any php errors visible?
In addition to above sub-url question, send em the htaccess file from /tips

**Comment by GRMacGeek** [comment]
I don't know where the "~servicemastergr1" is being generated from, that is actually my "Username" for my FTP and cPanel for this account... I don't know how/why Pulse is picking that up during the install... Attached is the htaccess file from /tips
[Dot_htaccess.txt](https://github.com/yuzoolcode/pulsecms-tracking/files/1693057/Dot_htaccess.txt)

**Comment by jrondorf** [comment]
That htaccess is wrong. Check the correct format here: https://instacks.com/pulsecmsstack/tutorial/#blog

Still that wrong htaccess file doesn’t explain the wrong URL generation. 

Already the original pulse blog page has these wrong links: https://www.servicemastergrandrapids.com/pulse/blog

@yuzoolcode any idea why these URLs on the original pulse blog page are having the ~servicemastergr1 username in it?

**Comment by GRMacGeek** [comment]
I fixed the htaccess file, but as you state, it doesn't fix the URL issue.

**Comment by jrondorf** [comment]
As the original generated links are already wrong, the RW Integration Stack isn’t able to replace them correctly to work inside RW. That will also explain most or all of the other issues you opened.

**Comment by ghost** [comment]
Why is the URL adding your account username?
~servicemastergr1

This needs testing as it's not happening in my testing environments.

Where are you hosting?

**Comment by GRMacGeek** [comment]
Okay - I did a couple of things - instead of "upgrading" Pulse 5, I put in a "fresh install" of 5.02 This has fixed the account username issue, it has disappeared. Something in the files we are not supposed to change (maybe the "pulsecore/storage/ (folder)"?) was probably the culprit.

However, still having URL issues, when you click any of the "blog tags" or "blog post" titles, not going to the right place...

Okay I use "Greengeeks"  reseller account for quite a few websites. I created a "blank" account for you on a URL I am not really using right now, and will email you the cPanel/FTP details. Go nuts, use it for testing!

**Comment by ghost** [comment]
Thanks Raimo for helping test with this

**Comment by ghost** [comment]
Fixed in 5.0.3:
http://help.pulsecms.com/article/10-version-history

The path detection code uses $_SERVER['REQUEST_URI'] so odds are theres some kind of url rewrite before Pulse sees the request. I think the quick fix would be to manually edit the .htaccess and config.json path.

However, a better fix would be to show the path in the installer and allow the user to edit it. This is now an option with the install - so amend where necessary.

- redownload and make a fresh install of all files
- run the installer

Should work 😀

**Comment by GRMacGeek** [comment]
Nothing changed... blog links (tags, titles, pages) go nowhere... There was no prompt during install process to change path... 

I did notice in the "settings" page that it says I am running v5.0.1 - are we having download issues again? Or am I actually running 5.0.3? Where can I go to see?

![pulse_cms](https://user-images.githubusercontent.com/6706155/35920556-2c5837b8-0be6-11e8-834f-4ab95daed3c2.jpg)

**Comment by IvaRoSoft** [comment]
Shown correctly V. 5.0.3
To avoid any deficiencies like V5.0.2
File to download "pulse5.zip" named after version, for example: "pulse5.0.3.zip"

**Comment by ghost** [comment]
Thanks @GRMacGeek - not sure why this happened. Just downloaded from the server now and 5.0.3 is on there.

Check config.php and you should see 5.0.3 and let me know.
If not, logout and login to dashboard again and try the download again...
