### ISSUE TITLE
Blog does not show in v5.0.2

### ISSUE THREAD

**Issue by oliver-77** [yuzoolcode/pulsecms-tracking#19]
This is what I get when I try to open the blog page:

![blog-error](https://user-images.githubusercontent.com/24696577/35811337-8740e0e8-0a8e-11e8-9fb8-2abaa5896355.png)

**Comment by ghost** [comment]
Fixed in 5.0.3:
http://help.pulsecms.com/article/10-version-history

Blog page bug is fixed. The dispatcher route matching is stricter

- redownload and make a fresh install of all files
- run the installer

Should work 😀
