### ISSUE TITLE
Date format in dashboard

### ISSUE THREAD

**Issue by oliver-77** [yuzoolcode/pulsecms-tracking#2]
Not really a bug but I think the date format in dashboard should change according to language. 
At the moment this is hardcoded.
`pulsecore/page/admin/dashboard.php` line 130/133

![dashboard-date](https://user-images.githubusercontent.com/24696577/33775270-1cb85da6-dc3e-11e7-9291-6be34aaf9518.png)

**Comment by ghost** [comment]
Fixed in 5.0.2! 😃👍
http://help.pulsecms.com/article/10-version-history
