### ISSUE TITLE
Blocs Compatibility with Pulse 5

### ISSUE THREAD

**Issue by nbouwsma** [yuzoolcode/pulsecms-tracking#21]
Shot this over in twitter but would like to track this here, so its official.

Hey @yuzool and @NormSheeran having a few issues with @blocsapp exporting to @pulse_cms.  Seems that some areas are exporting embedded "<?php echo $path; ?> code inline for media and links that is not being handled on the Pulse side.  Any update on Blocs compatibility with Pulse5

Validated this issue persists with 5.0.2 after recent repackaging.

**Comment by ghost** [comment]
This is the tweet:
https://twitter.com/blocsapp/status/957691092274688000

We can keep this open but it's not something that will change in a Pulse update. It will appear in a Blocs app update. I think it's scheduled for Blocs 2.5

**Comment by ghost** [comment]
https://forum.blocsapp.com/t/new-to-pulse-porting-blocs-to-pulse/2692/14?u=pulsecms

**Comment by ghost** [comment]
This has been done!
https://forum.blocsapp.com/t/new-to-pulse-porting-blocs-to-pulse/2692/15?u=pulsecms
