### ISSUE TITLE
Incorrect installations

### ISSUE THREAD

**Issue by IvaRoSoft** [yuzoolcode/pulsecms-tracking#22]
I have not succeeded in installing 5.0.2.
Error on localhost
Error on:
[https://pulse5.000webhostapp.com/](https://pulse5.000webhostapp.com/)
[http://ivarosoft.wz.sk/](http://ivarosoft.wz.sk/)

Errors described on:
[https://ivarosoft.000webhostapp.com/blog-1000-a-mistake-pulse5](https://ivarosoft.000webhostapp.com/blog-1000-a-mistake-pulse5)

Please!!! Can you help me?
Are these errors known?
It correctly when pulse forms a new file?
![root_ivarosoft wz](https://user-images.githubusercontent.com/29908185/35865567-2554841c-0b55-11e8-9808-7c8ca93c6963.png)
![root-pulse5 000](https://user-images.githubusercontent.com/29908185/35865589-31f277e2-0b55-11e8-89ec-846e2e651db8.png)

**Comment by ghost** [comment]
Known errors @IvaRoSoft  as I messaged you :) 

Update coming soon

**Comment by ghost** [comment]
Fixed in 5.0.3:
http://help.pulsecms.com/article/10-version-history

- redownload and make a fresh install of all files
- run the installer

Should work :)
