### ISSUE TITLE
Wrong content header in tracker.php - pulse 5.0.3

### ISSUE THREAD

**Issue by jetwes** [yuzoolcode/pulsecms-tracking#23]
If you run your server with "nosniff" option to prevent content type sniffing (which is recommended to do) you get an error in the frontend:
`Refused to execute script from 'tracker.php?uri=/&ref=none' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`

You can fix this by adding `header('Content-Type: application/javascript');` to tracker.php

**Comment by ghost** [comment]
Will add this in next update

**Comment by ghost** [comment]
Added in 5.1
