### ISSUE TITLE
Missing css error in admin - pulse 5.0.3

### ISSUE THREAD

**Issue by jetwes** [yuzoolcode/pulsecms-tracking#24]
In the admin section there is an error for a missing css:
 pulsecore/asset/vendor/node_modules/sweetalert/dist/sweetalert.css

There is no need to import an external css file for sweetalert2 any more - just disable the import in admin/index.php on line 79. The styles are bundled in JS with sweetalert2 

Furthermore there is a deprecation warning for "confirmButtonText".
Fix: 

> confirmButtonText and cancelButtonText are no longer needed. Instead, you can set button: "foo" to set the text on the confirm button to "foo", or buttons: ["foo", "bar"] to set the text on the cancel button to "foo" and the text on the confirm button to "bar".

Info: [https://sweetalert.js.org/guides/#upgrading-from-1x](url)

**Comment by ghost** [comment]
Will add this is next update

**Comment by ghost** [comment]
Added in 5.1
