### ISSUE TITLE
 Blog - "Back" button error.

### ISSUE THREAD

**Issue by IvaRoSoft** [yuzoolcode/pulsecms-tracking#25]
Pulse V5.0.3
A: Blog - "Back" button error.
1. - Searching for a blog
2. - View from found blog
3 - use the "back" (link: https://website.com/blog)
4. - Error:
"
Confirm reissue of the form
-
-
ERR_CACHE_MISS
"
5. - Using the "Reset Page"
!!! Tested multiple times, the bug repeats itself!

**Comment by ghost** [comment]
Sure - this can be improved with a relative link rather than JS

**Comment by ghost** [comment]
Added in 5.1
