### ISSUE TITLE
Blog tags

### ISSUE THREAD

**Issue by IvaRoSoft** [yuzoolcode/pulsecms-tracking#27]
C: Blog tags
1. - If you select a link in Blog tags, such as "apple" in your blog.
Viewing "apple" posts
Back to all blog posts (???).
He has to use the main menu.
- Admin to create a link to: "website.com/blog", or
- (B :) - ($ lang_blog_view_tags = 'Blog tags';)
   to use as a reference to "website.com/blog"
   That's just my thought.

**Comment by ghost** [comment]
Or an "all" tag category?

**Comment by IvaRoSoft** [comment]
The website must be friendly for site visitors.

**Comment by ghost** [comment]
Added in 5.1
