### ISSUE TITLE
Blog pager button

### ISSUE THREAD

**Issue by IvaRoSoft** [yuzoolcode/pulsecms-tracking#28]
D: Blog pager button
Blog, choose the tag "products"
One post will be displayed.
Click on the pager "1" (the articles)
You will be redirected to:
"Website.com/tagged/blog-page-1?blog_name="
Blog tag will be: "blog-page-1"
Viewing blog post = no.

**Comment by ghost** [comment]
Thanks - good catch - will add in next update

**Comment by ghost** [comment]
Added in 5.1
