### ISSUE TITLE
Rename file.jpg (error)

### ISSUE THREAD

**Issue by IvaRoSoft** [yuzoolcode/pulsecms-tracking#29]
Pulse 5.0.3
Rename file.jpg (error)
Can not rename file.jpg in galleries.
You reported an error: "Unknown extension detected".
Already how many years you support this error?

![rename1](https://user-images.githubusercontent.com/29908185/36243898-27f23fb8-1224-11e8-9de2-01dbcfef7b26.png)
![rename2](https://user-images.githubusercontent.com/29908185/36243899-2f26cfc4-1224-11e8-94c4-95cf450b2433.png)

It is not possible to rename the folder in the media.
Do not report any error!

**Comment by ghost** [comment]
Definitely a bug in the rename code (confirmed) and will be fixed in 5.1 release

**Comment by ghost** [comment]
Fixed and will be in next 5.1 BETA or final release
