### ISSUE TITLE
Creating a new "Folder" in blocks, pages and media is hardcoded

### ISSUE THREAD

**Issue by oliver-77** [yuzoolcode/pulsecms-tracking#3]
When creating a new folder in blocks, pages or media, the word "Folder" doesn't change according to language.

![new-block-page-media](https://user-images.githubusercontent.com/24696577/33793690-137337f6-dcbc-11e7-9116-c16125e9a64a.png)

`admin/inc/create.php` line 197
`<?php echo (\stripos($folder, 'blog') === false) ? 'Folder' : 'Blog'; ?>` 

Possible solution:
`<?php echo (\stripos($folder, 'blog') === false) ? $lang_create_item_folder : 'Blog'; ?>`

New lang string around line 98
`$lang_create_item_folder = 'Ordner';`

![folder](https://user-images.githubusercontent.com/24696577/33793686-0c1e87bc-dcbc-11e7-89b1-d4ea75d5f5f6.png)

**Comment by ghost** [comment]
@IvaRoSoft for translations also :)

**Comment by ghost** [comment]
Fixed in 5.0.2! 😃👍
http://help.pulsecms.com/article/10-version-history
