### ISSUE TITLE
Deprecated warning for localizer since PHP 7.2

### ISSUE THREAD

**Issue by oliver-77** [yuzoolcode/pulsecms-tracking#30]
When I use localizer on a page using PHP 7.2.2 I get the following warning:

`Deprecated: parse_str(): Calling parse_str() without the result argument is deprecated in D:\xampp\htdocs\Pulse503\inc\tags\localizer_init.php on line 7`

Until version 7.1.4 I did not see this warning.

**Comment by jrondorf** [comment]
Thanks, fixed for 5.1.

**Comment by ghost** [comment]
Done - great work @jrondorf !
