### ISSUE TITLE
Can not save settings in Pulse 5.03 when there are many blocks

### ISSUE THREAD

**Issue by oliver-77** [yuzoolcode/pulsecms-tracking#34]
If I have many blocks created, Pulse does not save the settings under Account.

**Comment by ghost** [comment]
Will look at this for the next update.

- how many is "many"?
- and do you meant the admin settings page is not saving or the blocks content changes?

Thanks

**Comment by oliver-77** [comment]
At the moment I have more than 200 blocks but I would say the problem starts when you have more than 100 or 150.

Yes I mean the admin settings, you click on save, the site refreshes (without sweetalert) and nothing happend/saved

**Comment by ghost** [comment]
Thanks will take a look

**Comment by oliver-77** [comment]
I've noticed something else. In the admin settings of the editor user all blocks are listed and activated. In the block area the block with the many entries/blocks is missing for the editor user. The admin user can see and edit them.

**Comment by ghost** [comment]
Sounds like a different issue - opened that here:
https://github.com/yuzoolcode/pulsecms-tracking/issues/35

**Comment by ghost** [comment]
Needs more testing but we'll catch this in 5.1

**Comment by ghost** [comment]
Its not related to Blocks listed in Editor user. This worked when I tested. Not sure how many blocks I should be trying to test with ?

Maybe easier if you forum DM or Slack zip send your project that shows this?

**Comment by ghost** [comment]
This is around the php ini max_input_vars setting. The default is around 1000.

I've fixed a bug in the session where there were duplicates of some of the checkboxes. That gets the settings form submit working for the test case of around 300 posts.

For large numbers of blocks - somewhere around 400 - 500. The fix would be for users to adjust their php.ini file and raise the limits.

Added a manual note on increasing PHP.ini to get around this:


> NB: For large sites with Blocks somewhere around 400-500 it might be necessary to increase the server max input variables (max_input_vars) PHP memory limit. Do this on your server via the php.ini or .htaccess file and try something like max_input_vars = 3000;     See your host's wiki on the correct method to adjust this for your server. For example with GoDaddy like this.

**Comment by oliver-77** [comment]
Sorry, I forgot to check on Github.
Do you still need some data or should I test it with the last Beta 2?
Would that have to work?

**Comment by ghost** [comment]
No worries @oliver-77 
Please test with BETA2 and use the php.ini commands as in 
https://github.com/yuzoolcode/pulsecms-tracking/issues/34#issuecomment-379946514
👍
