### ISSUE TITLE
Translation update of plugins for Redactor.

### ISSUE THREAD

**Issue by IvaRoSoft** [yuzoolcode/pulsecms-tracking#36]
Translation update of plugins for Redactor.
Fixed script is on:
https://github.com/IvaRoSoft/Redactor_3_langs

**Comment by ghost** [comment]
Thanks for the Dutch @IvaRoSoft 
Was this from Mary?

- This will be in the next build
- I'm not sure what else had changed as the format was different to how Pulse requires
- I went through each lang string and looked same for PL, CS, SK and HU as you submitted before
- If I missed something please let me know by syncing with the lang.pulse file and adding it in the format as shown here: https://github.com/yuzoolcode/pulsecms-languages/blob/master/pulse%205/shipping-with/Redactor%20Plugins/lang.pulse.js
- _Please pull first before pushing_
- Your file here is in a different format and we don't need two copies of the same thing:
https://github.com/IvaRoSoft/Redactor_3_langs/blob/master/Plugins_langs/lang.pulse.js

Thanks for submitting :)

**Comment by IvaRoSoft** [comment]
I translated the Dutch translation myself.
I used my archive.
I rename the github file to "plugins.langs (full) .js".
The script works great in other redactor installations.

Adwords translations for Redactor are not working properly.
Localhost: Firefox = ok, Chrome = false.
Web server: Firefox + Cchrome = false.

There are a few mistakes there:
localhost: overridden website address
"Http: // localhost / pulsecms51b1 / pulsecms51b1 / about"
Markdown text is not displayed correctly.

I will test the pulse, then write specifically.

**Comment by yuzoolcode** [comment]
> Adwords translations for Redactor are not working properly.
> Localhost: Firefox = ok, Chrome = false.
> Web server: Firefox + Cchrome = false.

By @IvaRoSoft

**Comment by ghost** [comment]
> Adwords translations for Redactor are not working properly.
> Localhost: Firefox = ok, Chrome = false.
> Web server: Firefox + Cchrome = false.

**Comment by IvaRoSoft** [comment]
My error in the text. ( no Adwords), "addons"
Translated add-ons for Redactor are not working properly.
Or they do not work at all

**Comment by ghost** [comment]
Plugins?

**Comment by IvaRoSoft** [comment]
Yes, plugin translation does not work

**Comment by ghost** [comment]
I switched the translation to japanese and that worked. Tested redactor too. Is this happening for a specific language, or on a specific page? @IvaRoSoft

**Comment by IvaRoSoft** [comment]
All languages
I will send the access password to the forum.

**Comment by ghost** [comment]
Lang now loading correctly.

The lang.pulse.js was setting up the new languages but not adding them in the $R.addLang call.

This will be in the next BETA for 5.1
