### ISSUE TITLE
 localhost: overridden website address

### ISSUE THREAD

**Issue by ghost** [yuzoolcode/pulsecms-tracking#37]
> localhost: overridden website address
> "Http: // localhost / pulsecms51b1 / pulsecms51b1 / about"
> Markdown text is not displayed correctly.
> 
> 

From @IvaRoSoft

**Comment by IvaRoSoft** [comment]
Two independent attempts to install on localhost.
Used Firefox
First save the setting:
Unable to save settings, Firefox drops.
Open in Chrome = setting saved, error in page address.
Installation removed.
Second install, use Chrome.
Saving Administrator Settings:
Chrome writes:
"Too many login failures."
Admin can not be displayed.
Restart the server.
Incorrect address:
"Http: // localhost / pulsecms51b1 / pulsecms51b1 / about"
.............. WEB .......
The menu on the page is not displayed.
Menu manager, without editing saved.

At: https://pulse5.000webhostapp.com/
Result: "about: blank".

At: http://pulse.wz.sk/home
Result: "http: //pulse.wz.skabout/"

**Comment by ghost** [comment]
@IvaRoSoft 
Looking at this, I'm not sure what it means. 

The path in Http: // localhost / pulsecms51b1 / pulsecms51b1 / about has pulsecms51b1 repeated, so that might be a factor. 

A look at the htaccess and config file might help - also details on the install path - can you send those please as DM on the forum?

I wonder if you are using the installer? 

What are the login errors? Are you using the password and too many attempts? Clear cache or different browser might help for the login errors

**Comment by IvaRoSoft** [comment]
1, After uploading to localhost = install.php = login = change setting + save = errors.
Firefox or Chrome
Browser Error = "Too many login failures."

In one instance, the page was able to run.
Evil Address:
"Http: // localhost / pulsecms51b1 / pulsecms51b1 / about"

There is also a bad address on the web.

**Comment by jrondorf** [comment]
@IvaRoSoft 

> After uploading to localhost

What are you doing here exactly? Details please.

**Comment by IvaRoSoft** [comment]
Repeat!
localhost:
The first save of the administrator's configuration ends with a browser error.
Only "Too many login failures."
Restart localhost, the page appears.
The menu selection "about" = error.
All pages = error.

..............
How he works on the web: View the site's links to the previous post.

**Comment by jrondorf** [comment]
What are you using? MAMP?

**Comment by IvaRoSoft** [comment]
XAMPP Version: 7.1.8
I will manage the third installation attempt on a clean localhost
  I'll let you know.

**Comment by IvaRoSoft** [comment]
Third attempt.
The browser can not save settings (Chrome)
![screenshot - 31_3 002](https://user-images.githubusercontent.com/29908185/38162736-426aee36-34e7-11e8-929b-3964a4a7ad10.png)

Restart
Saving approx. 5 minutes.
Site Address:
http: // localhost / pulse1b1-3 / pulse1b1-3 / about

The correct address is:
http: // localhost / pulse1b1-3 / about

![screenshot - 31_3 006](https://user-images.githubusercontent.com/29908185/38163433-5c763d46-34f4-11e8-898c-3eba0b5a6ef8.png)

**Comment by ghost** [comment]
The bug is the repeated / pulse1b1-3 I think a look at the config files and the .htaccess is something we need. Can you send via the forum?

If not I'll have to get xampp 7.1.8 and see if its something related to that. Its a later PHP version than I'm using for development.

**Comment by IvaRoSoft** [comment]
Already I am using a newer version of XAMPP
"
Windows Version:  Pro  64-bit
XAMPP Version: 7.2.3
"
.htaccess will send you.
There is only one change.
"RewriteBase /pulsetest"

I changed the directory.
I changed the version of Pulse 5.0.3
The error is repeated.

**Comment by ghost** [comment]
Thanks please send me :) 

With the new installer since 5.0.3 at least, you don't need to adapt the htaccess - so no changes in htaccess needed.

**Comment by ghost** [comment]
Plugged in an update for the navigation bugs to go out in 5.1BETA2 later this month.

I've tested in PHP 7.2.3 and that works too.
We will run Unit tests before the release to make sure it passes those also :)
