### ISSUE TITLE
Root directory

### ISSUE THREAD

**Issue by IvaRoSoft** [yuzoolcode/pulsecms-tracking#38]
Generally, version 51b1
The root directory contains .bpup.php files.
Sometimes there are more files.
Does not interfere with the wrong operation Pulse?

![screenshot - 31_3 003](https://user-images.githubusercontent.com/29908185/38163073-4e65cf06-34ee-11e8-872f-f83f73423e31.png)

**Comment by ghost** [comment]
Yes - these backups do you not effect Pulse running (are there for backups purposes) and are created when the installer is ran. These can be deleted - or kept as backup files :)
