### ISSUE TITLE
Markdown

### ISSUE THREAD

**Issue by IvaRoSoft** [yuzoolcode/pulsecms-tracking#39]
Generally, version 51b1
Incorrect pageview = localhost
Display Text = markdown

![screenshot - 31_3 004](https://user-images.githubusercontent.com/29908185/38163146-29eed45a-34ef-11e8-8a69-d2a883b50491.png)

**Comment by ghost** [comment]
This is only for logged in users and not website visitors

It's not a major issue and in some cases desirable. 
That said, parsedown was switched off in the inline edit mode in 5.1BETA so we can look at this again.

**Comment by ghost** [comment]
Markdown will appear, but wont be expanded/parsed until the user logs out 
End users can see the parsed Markdown
