### ISSUE TITLE
Blog search

### ISSUE THREAD

**Issue by IvaRoSoft** [yuzoolcode/pulsecms-tracking#40]
Generally, version 51b1
Blog search.
"The joy of website visitors must be great"
What does this code say to a site visitor?

![screenshot - 31_3 005](https://user-images.githubusercontent.com/29908185/38163238-0047f51c-34f1-11e8-8f40-e7e70492500b.png)

**Comment by ghost** [comment]
Search was improved in 5.0.2:
https://github.com/yuzoolcode/pulsecms-tracking/issues/8

That said, looks like there is some `##more##`  and `\r\n` code appearing which we can tidy up for the next update

**Comment by ghost** [comment]
This is cleaned up and improved in 5.1BETA2!
