### ISSUE TITLE
Set up menu

### ISSUE THREAD

**Issue by IvaRoSoft** [yuzoolcode/pulsecms-tracking#41]
Generally, version 51b1
Localhost, menu
This is an incorrect setting for site navigation.

![screenshot - 31_3 006](https://user-images.githubusercontent.com/29908185/38163410-06395896-34f4-11e8-8bee-ba46308da2c9.png)

**Comment by ghost** [comment]
Is this related to https://github.com/yuzoolcode/pulsecms-tracking/issues/37#issuecomment-377686659 ?

**Comment by ghost** [comment]
As this site and #37 is being developed locally, can you zip and forum DM me a download link of the site to run locally and test?

**Comment by ghost** [comment]
I'm not sure what the menu bug is. Is it the path or that things are packed into all ?

**Comment by ghost** [comment]
See:
https://github.com/yuzoolcode/pulsecms-tracking/issues/37#issuecomment-379940523
