### ISSUE TITLE
Logo Made in Pulse

### ISSUE THREAD

**Issue by IvaRoSoft** [yuzoolcode/pulsecms-tracking#42]
Logo Made in Pulse
By license, I can replace the logo.
That's very good.
However, you need to move the Made in Pulse logo "logo.svg"
to the admin folder, or the like.
Made in Pulse displays the logo for admin.
![logot - 2_4](https://user-images.githubusercontent.com/29908185/38206809-188b0f58-36ac-11e8-97e7-10daa4a34138.png)

**Comment by ghost** [comment]
Not sure on this one - the "Made in Pulse" badge is to show "Made in Pulse" - does it need rebranding? There is an option to switch it off in settings.

Users can rebrand easily the login and dashboard with their own logo by replacing the logo in Media. 

Logo.svg is in Media folder so is replaceable already.

**Comment by IvaRoSoft** [comment]
That is clear to me.
I had the impression that the Made in Pulse logo,
you want to keep it as the Pulse logo.
Because it links to your website.
