### ISSUE TITLE
Problems using Blocs 2.5.2 + Pulse 5.1 b3

### ISSUE THREAD

**Issue by wardiam** [yuzoolcode/pulsecms-tracking#44]
Hi,

I’m using Blocs 2.5.2 and PulseCMS 5.1beta3 to build my website: https://www.elrincondelcarpfishing.com/blog/. My website works perfectly inside Blocs (using toggle mode) but when I have exported my project as Pulse 5 template and I have uploaded it to my webserver, I have detected several bugs: (you can check in my website)

- Links: when I click on the link "BLOG" (button or NavMenu), the link is broken because the subfolder path is not detected and instead of putting the path of the subfolder this code appears `<?php echo $path; ?>/blog` in the navigation menu links (when I click on BLOG link).

- Images: also I have the same error in the link to several images that I have added to the main page. The images are not shown because the link is wrong again due to the addition of this code `<?php echo $path; ?>`.

- Text Class used in Footer: several text blocks are formatted with the class "category2" in the footer, but only those that have links to an email address or another web page are seen correctly, whereas the "normal" text blocks are black and I do not see them well, why? 

Could you help me, please?

Best regards,
Wardiam

**Comment by ghost** [comment]
- Is the sub path shown in the Pulse settings in Admin?
- Did you also run the Pulse install?

**Comment by ghost** [comment]
Reference:

https://forum.blocsapp.com/t/blocs-2-5-2-pulse-5-1-b1/3355

**Comment by ghost** [comment]
Also see:
https://forum.pulsecms.com/t/advice-for-importing-a-blocs-site-into-pulse5-cms/1000/15

**Comment by ghost** [comment]
Fixed in Blocs 2.6.0 BETA 6 Build:
https://forum.blocsapp.com/t/blocs-2-6-0-beta-build-6/3858
