### ISSUE TITLE
Subdomain

### ISSUE THREAD

**Issue by IvaRoSoft** [yuzoolcode/pulsecms-tracking#45]
Pulse 51b3
An attempt to install a Pulse on a subdomain.
Can not save the setting.
Is the subdomain a problem for Pulse?

**Comment by wardiam** [comment]
Hi IvaroSoft,

I could install pulseCMS 5.1b3 on a subfolder uploading pulsecms into this subfolder and adding this subfolder in the admin-pulse section. I see your url and you have installed pulse on the main domain.

Wardiam

**Comment by IvaRoSoft** [comment]
You can install the pulse into a subfolder.
Theoretically, you can also have three subfolders and every other pulse.

Possible contact: ivarosoft@gmail.com

**Comment by IvaRoSoft** [comment]
Problem solved.
I created a separate ftp account.
This is not good as the file properties change.
Will change: the owner / group.

Do not create a separate connection via ftp to the subdomain.
