### ISSUE TITLE
my posts are full of symbols

### ISSUE THREAD

**Issue by observatoire** [yuzoolcode/pulsecms-tracking#46]
Hello,

Since I moved to Pulse 5, I cannot write new post as they are like encrypted with symbols. I have tried a dozen of reinstallation. All the permissions are good. Then all my new posts have these kind of symbols
Blog : http://observatoire.fr/blog
<img width="1086" alt="capto_capture 2018-04-30_05-05-18_pm" src="https://user-images.githubusercontent.com/38861011/39434365-b4a3ccd4-4c98-11e8-8af3-cb89d6c28d85.png">

Thanks

**Comment by ghost** [comment]
Glad this was solved

**Comment by observatoire** [comment]
This is not totally… But I have other problem right now so I must try another clean install. But the symbols were due to an old version of the stack used. I did not know the stack had to be bought again and thought it was updated like any other stack…

**Comment by jrondorf** [comment]
Also other stacks create new major versions...

**Comment by observatoire** [comment]
I am sorry I am not sure to understand this statement...

**Comment by ghost** [comment]
@observatoire Pulse5 requires Pulse5 stacks for running in RapidWeaver sites:
https://instacks.com/pulsecmsstack/
