### ISSUE TITLE
gallery image delete and gallery.txt not properly updated issue

### ISSUE THREAD

**Issue by sryu** [yuzoolcode/pulsecms-tracking#47]
I add and delete images in the gallery. When I add caption to some images, they are stored in gallery.txt file by pulse (I am using v5.1b3). When I delete some images, the gallery.txt doesn't seem to delete the matching records accordingly. 

A side effect of this is that when I use the Pulse 5 Stack (by instacks) to display the images of the gallery in Rapid Weaver designed web pages, the deleted images still persist with empty space. Only when I manually edit the gallery.txt file, the issue is resolved.

**Comment by ghost** [comment]
Thanks - will take a look at this and get a fix into 5.1 final release.
Beta 4 out shortly ..

**Comment by ghost** [comment]
The delete code was regenerating the gallery file on delete. There was a bug on around the slashes in the pathname. That's fixed now and will be out in the next update 👍
