### ISSUE TITLE
Settings and page rewriting

### ISSUE THREAD

**Issue by IvaRoSoft** [yuzoolcode/pulsecms-tracking#5]
Sorry to bother!
I met the same mistakes.
On my test server (I have only 50 MB.) Ivaro.php5.sk (php = 7)
I had the impression that there was little room to make problems.
That's why I installed Pulse on http://ivarosoft.wz.sk/.
problems:
1.)
If I save the page, JSSON will be assigned to the first line
and the page is completely gone, it loses its form.
Do I make errors in the mete setting?

// Edited

**Comment by ghost** [comment]
Thanks @IvaRoSoft - there's multiple issues in here again.

Let me edit this and split them out and make separate issues. Please for next time make 1 issue per issue :) 

Thanks

**Comment by ghost** [comment]
@IvaRoSoft  The file should have JSON as the first line. That stores the META info. 
Can you send a screen shot of the broken page? Which page on http://ivarosoft.wz.sk/ was it?

**Comment by IvaRoSoft** [comment]
Site broke down because I set the editing pages Reactor.
I did not write a single word.
I gave the order to store.
He lost my taste for concern with Pulse.
In two days, I fixed it (without a redactor).
