### ISSUE TITLE
Blocks >> Footer link edit broken

### ISSUE THREAD

**Issue by sryu** [yuzoolcode/pulsecms-tracking#50]
I tried replacing (rather correcting) the links "Privacy" and "Admin" in the Blocks >> Footer. The reason is that I have pulse installed as subdirectory, yet those default links were pointing to as if pulse was installed at the root dir. So had to modify it like www.xxxx.com/pulse/admin. I also wanted to remove that Acme Copyright text, etc. 

When I save after replacing the links and text, and open the Home page again, I always get the result screwed up. The rendered html display something like this at the footer area: 

======
JSON_START{"html":"
Copyright My Company 2018 | Privacy | Get Pulse | Admin<\/p>","meta_searchable":"yes","title":""}JSON_END

Copyright My Company 2018 | Privacy | Get Pulse | Admin
=======

**Comment by ghost** [comment]
OK I see it - we'll get this fixed in next update.

In the meantime, please create a new footer Block and it should work fine :)

**Comment by ghost** [comment]
Confirmed instance 2:
http://pulse.miguelsla.com

**Comment by ghost** [comment]
Fixed in next BETA
Add prefixing the site urls with {{show_var:path}

e.g.

`<a href="{{show_var:path}}/privacy">Privacy</a>`
