### ISSUE TITLE
Pulse blog and P5 blog issue

### ISSUE THREAD

**Issue by sryu** [yuzoolcode/pulsecms-tracking#51]
Using Pulse v51b3 and b4 (installed in subfolder /pulse), along with InStacks' pulse integration stack, I  set up a Rapid Weaver page (named "news") to deliver the blog content using the P5 Integrator and P5 Blog stacks. While the setup works well when the pulse is installed in the public_html level, I encountered several anomalies in the case pulse is in /pulse. 

Note that the InStack's instruction is to place a .htaccess file inside the blog page (i.e. /news in my case) with the following content: 

   RewriteEngine On
   RewriteBase /news
   RewriteRule ^blog-tag-([^-]*)+? ?p=blog&blog_tag_name=$1 [L,QSA]
   RewriteRule ^blog-page-([^-]*)$ ?page=$1&p=blog [L,QSA]
   RewriteRule ^blog-([^-]*)+? ?d=$1&p=blog [L,QSA]

Problem: 
The blogs are displayed fine, but when I click on a blog article, and press the "back" button, it fails to go back to the original blog front page. When I examine where the link is headed to, I find it is taking me to /news/blog  (instead of /news). There is that redundant /blog added, and it is not properly redirected via the .htaccess file, it seems. 

With my very limited knowledge on grep and .htaccess, I managed to fix it by adding the following line at the end of the .htaccess : 

 **RewriteRule ^blog([^-]*)$ $1 [L,QSA]**

which I think removes any occurrence of "blog" that is not followed by a "-". In my case, it turns /new/blog to /news. Although this is OK for now at least for me, but I can anticipate side effects if one chooses to call his RW page "blog" or something. Also, I am not 100 % sure about the safety or validity about the line I devised above. 

It seems both Pulse5 and InStacks team should coordinate to resolve this issue properly?

**Comment by jrondorf** [comment]
Already fixed in stacks beta. Version send out to you by email.

**Comment by sryu** [comment]
that was a crazy fast response! Checked with the replaced P5Stack, and it seems to work fine. Just had to republish all files to clear the cache. Thanks.
