### ISSUE TITLE
Problems with Editor account (5.1b4)

### ISSUE THREAD

**Issue by wardiam** [yuzoolcode/pulsecms-tracking#52]
Hi,

I have two problems if the editor session is used:

1. If editor creates a new post on the blog and save it. If you try to edit the post again from the editor or admin session, you will not be able to edit it and the message "Content not found" will be displayed.

2. If editor creates a new folder to add multimedia content and clicks on the "upload" button to add the content, instead of showing the file upload dialog, he goes back to the main window of the dashboard.

Could you check these bugs, please?

Thank you very much.

Best regards,
Sergio

**Comment by ghost** [comment]
Thanks Sergio for the bug report

We'll check these out and if can confirm will get in next release or ask you for more info.

Cheers

**Comment by ghost** [comment]
@wardiam 

_Completed:_
2. Has been fixed for 5.1 BETA5.

_Question:_
1. The upload page was checking the editor list of approved pages from the configs. The blog add/edit works for both admins and editors. So I cant replicate that part of the bug.

Is the blog page in the list of pages approved by the admin for the editor?

**Comment by ghost** [comment]
This seems to be fixed now - both 1+2 completed so closing this for now and shipping 5.1BETA5 soon.

If you have any further issues, please just get in touch about this here :)
