### ISSUE TITLE
RSS Date Issue

### ISSUE THREAD

**Issue by unluckytoe** [yuzoolcode/pulsecms-tracking#55]
The RSS feed dates are still wicked wrong, like 100 years into the future wrong.

I have updated to 5.1 via the update button within the dashboard.

Check out https://deafgoats.com/pulse/rss.php

**Comment by ghost** [comment]
Hmmmmm..

I just did a clean 5.1 install and added a new post and here's the RSS:

![2018-06-19 at 15 11](https://user-images.githubusercontent.com/4608547/41579774-4d43f836-73d3-11e8-920d-03ccf9c26b93.jpg)

Shows today's date

I suspect there's something else at play here, could be server related or something else?

**Comment by unluckytoe** [comment]
Ok, it would appear that the pulsecore/page/rss.php did not update. Maybe it's possible that the auto updater did not work properly?

**Comment by ghost** [comment]
No I think it would have worked (most likely) and this might actually be RSS integration with Pulse+RapidWeaver. If that's the case, it will be in the Stack update.

**Comment by ghost** [comment]
Or did you manually swap the pulsecore/page/rss.php and it fixed it?

**Comment by unluckytoe** [comment]
I manually swapped the file.

Brian

**Comment by ghost** [comment]
Great - glad it's fixed.
