### ISSUE TITLE
JSON code appearing after save

### ISSUE THREAD

**Issue by ghost** [yuzoolcode/pulsecms-tracking#58]
> JSON_START{"html":"
> Copyright Cake Spirit. 2018 | Privacy policy here <\/a><\/p>\r\n
> 
> <\/figure>","meta_searchable":"yes","title":""}JSON_END
> Copyright Cake Spirit. 2018 | Privacy policy here
> 
> So I went and removed the image to see what that would do, and code is still there:
> 
> JSON_START{"html":"
> Copyright Cake Spirit. 2018 | Privacy policy here <\/a><\/p>\r\n
> 
> <\/figure>","meta_searchable":"yes","title":""}JSON_END
> Copyright Cake Spirit. 2018 | Privacy policy here

https://forum.pulsecms.com/t/loads-of-json-code-apeared-on-page-after-editing-a-block/1093

**Comment by ghost** [comment]
Is this related to https://github.com/yuzoolcode/pulsecms-tracking/issues/50 as it's the footer; or is it happening in all Blocks?

**Comment by jdloudon** [comment]
Seems to be just in footer, although I had a random instance of it happening in blog, but that seems to have gone now.
I tried deleting the block. Then made a new one containing just the image and it is still doing it. See the site now.
[debug_info.zip](https://github.com/yuzoolcode/pulsecms-tracking/files/2201042/debug_info.zip)

**Comment by ghost** [comment]
Thanks

The fix for links in the Footer is:
https://github.com/yuzoolcode/pulsecms-tracking/issues/50#issuecomment-394594302

Will look through the Debug info also

**Comment by jdloudon** [comment]
Thanks, but I still have the issue even without a link being there:

http://cakespirit.co.uk/

James

**Comment by ghost** [comment]
Just looking at the logs for that site and can see this error:

> [17-Jul-2018 10:22:22 Europe/London] PHP Warning:  include(content/blocks/footer.txt): failed to open stream: No such file or directory in /var/www/vhosts/cakespirit.co.uk/httpdocs/template/layout.php on line 45
> [17-Jul-2018 10:22:22 Europe/London] PHP Warning:  include(content/blocks/footer.txt): failed to open stream: No such file or directory in /var/www/vhosts/cakespirit.co.uk/httpdocs/template/layout.php on line 45
> [17-Jul-2018 10:22:22 Europe/London] PHP Warning:  include(): Failed opening 'content/blocks/footer.txt' for inclusion (include_path='.:/opt/plesk/php/7.0/share/pear') in /var/www/vhosts/cakespirit.co.uk/httpdocs/template/layout.php on line 45

Can you check:

1) Does the Footer.txt Block exist? In the Content Folder?
2) What does the layout.php have to point to the Block? Is it 	`<?php include("content/blocks/footer.txt"); ?>
` ?

**Comment by jdloudon** [comment]
Hello, yes that happened because I deleted the footer block as it was the
only way to get rid of the JSON code.
I have reinstated it now and as you can see I still have the fault.

**Comment by ghost** [comment]
Thanks

Now it exists - can you share the logs again as the error should be different :)

Thanks!

**Comment by jdloudon** [comment]
Okay, enclosed, thanks/

**Comment by ghost** [comment]
Can you attach them to this page as before? I think the email reply notification just removes the attachments... thanks

**Comment by jdloudon** [comment]
[debug_info(2).zip](https://github.com/yuzoolcode/pulsecms-tracking/files/2218429/debug_info.2.zip)

Here is latest debugs. Client wants to launch site now so I shall have to delete footer and just insert the logo hard coded into the layout template.
I still want this fixed though as we do want to use the footer are.
Note that now I cannot even edit it. I thought I might delete the logo from footer so its just blank but I could not even do that.
So I shall just go ahead and delete it with ftp.
![image](https://user-images.githubusercontent.com/40563526/43065108-b6911cb6-8e58-11e8-80a0-e859bdaf8871.jpg)

**Comment by ghost** [comment]
Great thanks James - that's a good solution for now.

Got the debug info and let us look at this and work it into the next update

**Comment by ghost** [comment]
The custom layout seems to be wrong and needs to be updated. I suspect you would be seeing some javascript errors around missing JS files. 

If possible, please update to Pulse 5.2 shortly and see if the issues appear again. 5.2 will be out soon.

In the meantime, checking the template custom layout with the example template or the manual might give a clue what is missing?

**Comment by jdloudon** [comment]
Hello, this site is pretty much using the standard template. All I did was changed the images and logo really. So I would say its not a custom layout.

**Comment by ghost** [comment]
OK - let's try it with the new version soon and see if that helps it. Hopefully it does!
