### ISSUE TITLE
Page content disapears in Safari after blog post creation

### ISSUE THREAD

**Issue by jdloudon** [yuzoolcode/pulsecms-tracking#59]
Hello, a client is having issues with this.
http://howtospeakchild.com/

The problem only manifests itself on a Mac using Safari.
If you create a post and then view the site onthe same browser **without logging out** then there is no page content to see - just the header, navigation and page container.

But log out first and it seems to be okay. I enclose the log files here.
I did have a peek at one of them and can see an error - but it relates to another domain altogether.

[06-Dec-2017 21:59:05 Asia/Tokyo] PHP Fatal error:  Uncaught exception 'LogicException' with message 'A pre-condition has failed' in /var/www/vhosts/twose.me.uk/httpdocs/pulsecore/dbc.php:12

twose.me.uk was a domain on my server for a while - I have no idea where this install of Pulse is getting that from. Nothing in any of the settings that relaes to that domain. Can you explain that?
Its very weird. Whether that has anything to do with the issue or not I dont know.

The site is using a home made template

[layout.zip](https://github.com/yuzoolcode/pulsecms-tracking/files/2218879/layout.zip)

[debug_info.zip](https://github.com/yuzoolcode/pulsecms-tracking/files/2218869/debug_info.zip)

**Comment by ghost** [comment]
Thanks @jdloudon  - we will need to test this and try and replicate what is going on.

We also run on Macs and Safari always seems to work ok.

Thanks

**Comment by ghost** [comment]
This is something on the server setup. 

Either there is a symbolic link or a virtual host with the same web root as the current install. 

Something must be running Pulse on that path or there would not be an error log entry.

**Comment by ghost** [comment]
Please try Pulse 5.2 BETA1 once it is out soon (August 2018) as should fix this issue. If not, please re-open this task!
