### ISSUE TITLE
Backspace/Delete - not working in a block containing a table..

### ISSUE THREAD

**Issue by junction10** [yuzoolcode/pulsecms-tracking#60]
The following is the complete HTML code I've pasted into a Pulse Block, for use in a Foundry Tabs stack..  It works great in my page..  but while trying to edit in the Pulse admin block editor, I've just noticed that I can't delete any text - my backspace key doesn't work..  It works while editing any other block with text, but not the block containing this table:

`<table style="display: table;" class="table  table-striped table-bordered  tablesorter">`
`<thead><tr>`
`<th colspan="1"></th>`
`<th colspan="1">`
`</th>`
`<th class="text-xs-center" colspan="1">Building Open`
`</th>`
`<th class="text-xs-center" colspan="2">Surgery Times`
`</th>`
`</tr>`
`</thead>`
`<tbody>`
`<tr>`
`  <td colspan="1">`
`  </td>`
`<td colspan="1">`
`</td>`
`<td colspan="1">`
`</td>`
`<th scope="row" class="text-xs-center" colspan="1">`
`AM`
`</th>`
`<th scope="row" class="text-xs-center" colspan="1">`
`PM`
`</th>`
`</tr>`
`<tr>`
`  <td colspan="1">`
`  Monday - Friday`
`</td>`
`<td colspan="1">`
`</td>`
`<td class="text-xs-center" colspan="1">`
`7:30am - 6:30pm`
`</td>`
`<td colspan="1"> `
`</td>`
`<td colspan="1">`
`  </td>`
`</tr>`
`<tr>`
`  <td colspan="1">Monday - Friday`
`</td>`
`<td colspan="1">`
`  GP</td>`
`<td colspan="1">`
`</td>`
`<td class="text-xs-center" colspan="1">`
`  8:00am - 12:00 noon`
`</td>`
`<td class="text-xs-center" colspan="1">`
`  3:00pm - 6:30pm`
`</td>`
`</tr>`
`<tr>`
`  <td colspan="1">`
`Mon, Tues, Thurs, Fri`
`</td>`
`<td colspan="1">`
`  ANP`
`</td>`
`<td colspan="1">`
`</td>`
`<td class="text-xs-center" colspan="1">`
`  7:30am - 12:30pm`
`</td>`
`<td class="text-xs-center" colspan="1">`
`  3:30pm - 5:30pm`
`</td>`
`</tr>`
`<tr>`
`  <td colspan="1">`
`  Monday - Friday`
`</td>`
`<td colspan="1">`
`  Nurse`
`</td>`
`<td colspan="1">` 
`</td>`
`<td class="text-xs-center" colspan="2">`
`  7:30am - 6:30pm`
`</td>`
`</tr>`
`<tr>`
`  <td colspan="1">`
`  Saturday`
`</td>`
`<td colspan="1">`
 ` GP / ANP / Nurse`
`</td>`
`<td colspan="1">`
`</td>`
`<td class="text-xs-center" colspan="2">`
`  8:00am - 10:00am`
`</td>`
`</tr>`
`<tr>`
`  <td colspan="1">`
`  Sunday`
`</td>`
`<td colspan="1">` 
`</td>`
`<td colspan="1">`
` </td>`
`<td class="text-xs-center" colspan="2"><div>`
`  Surgery Closed`
`</div></td>`
`</tr>`
`</tbody>`
`</table>`

and this is the table without the code tag:

<table style="display: table;" class="table  table-striped table-bordered  tablesorter">
<thead><tr>
<th colspan="1"></th>
<th colspan="1">
</th>
<th class="text-xs-center" colspan="1">Building Open
</th>
<th class="text-xs-center" colspan="2">Surgery Times
</th>
</tr>
</thead>

<tbody>
<tr>
  <td colspan="1">
  </td>
<td colspan="1">
</td>
<td colspan="1">
</td>
<th scope="row" class="text-xs-center" colspan="1">
AM
</th>
<th scope="row" class="text-xs-center" colspan="1">
PM
</th>
</tr>

<tr>
  <td colspan="1">
  Monday - Friday
</td>
<td colspan="1">
  
</td>
<td class="text-xs-center" colspan="1">
7:30am - 6:30pm
</td>
<td colspan="1"> 
</td>
<td colspan="1">
  </td>

</tr>

<tr>
  <td colspan="1">Monday - Friday
</td>
<td colspan="1">
  GP</td>
<td colspan="1">
  
</td>
<td class="text-xs-center" colspan="1">
  8:00am - 12:00 noon
</td>
<td class="text-xs-center" colspan="1">
  3:00pm - 6:30pm
</td>

</tr>

<tr>
  <td colspan="1">
Mon, Tues, Thurs, Fri
</td>
<td colspan="1">
  ANP
</td>
<td colspan="1">
  
</td>
<td class="text-xs-center" colspan="1">
  7:30am - 12:30pm
</td>
<td class="text-xs-center" colspan="1">
  3:30pm - 5:30pm
</td>

</tr>

<tr>
  <td colspan="1">
  Monday - Friday
</td>
<td colspan="1">
  Nurse
</td>
<td colspan="1">
  
</td>
<td class="text-xs-center" colspan="2">
  7:30am - 6:30pm
</td>

</tr>

<tr>
  <td colspan="1">
  Saturday
</td>
<td colspan="1">
  GP / ANP / Nurse
</td>
<td colspan="1">
  
</td>
<td class="text-xs-center" colspan="2">
  8:00am - 10:00am
</td>

</tr>

<tr>
  <td colspan="1">
  Sunday
</td>
<td colspan="1">
  
</td>
<td colspan="1">
 </td>
<td class="text-xs-center" colspan="2"><div>
  Surgery Closed
</div></td>
</tr>
</tbody>
</table>

Pulse 5.2b2, running locally on MAMP

**Comment by ghost** [comment]
Thanks for the report. Could be a Redactor issue or "backspace" disabled? 
Will test on this, thanks

**Comment by ghost** [comment]
Change this file in admin > redactor > plugins > table.min.js

(unzip firstly!) 

[table.min.js.zip](https://github.com/yuzoolcode/pulsecms-tracking/files/2464976/table.min.js.zip)

This will go in the next version - 5.2!

**Comment by ghost** [comment]
This was fixed in 5.2B4! :) 
https://forum.pulsecms.com/t/pulse-5-2beta4-release/1181
