### ISSUE TITLE
Can't upload images into blocks

### ISSUE THREAD

**Issue by GRMacGeek** [yuzoolcode/pulsecms-tracking#61]
I'm using 5.2b2 and Rapidweaver

- I can't upload images into any blocks. Just get a blue "loader" line across the top, but nothing ever uploads...
- I also can't choose any images already in the media folder, just get a blank "choice" box (image attached

As a work around for now, I have been adding images by going into the html and adding the links by hand. Once they are there, I can actually edit them in Pulse, just can't add them through the normal Pulse screens...
The website I'm working on is at [https://fiberprotectorwm.com/](https://fiberprotectorwm.com/)
![pulse_cms](https://user-images.githubusercontent.com/6706155/45896405-06b9ed80-bda2-11e8-95a8-34f8daced01c.jpg)

**Comment by ghost** [comment]
I think this is fixed in B3.. we detected this and have fixed it
That will be out soon and we can double-check this then! :)

**Comment by ghost** [comment]
Thanks again for reporting this.. it should be fixed in B3 released today:
https://forum.pulsecms.com/t/pulse-5-2beta3-has-been-released/1147
:)
