### ISSUE TITLE
Upload/delete images via FTP issue in 5.2b3

### ISSUE THREAD

**Issue by GRMacGeek** [yuzoolcode/pulsecms-tracking#62]
Using Pulse 5.2b3
Rapidweaver 8

Gallery 3 Stack is still trying to pull images that were deleted from the folder. 

- Link here to test page [https://fiberprotectorwm.com/test/](https://fiberprotectorwm.com/test/) Go down the right hand side under the contact us box
- Here is the same page using a P5 "Slider Stack" instead [https://fiberprotectorwm.com/](https://fiberprotectorwm.com/)

**Comment by jrondorf** [comment]
You know where the issue comes from, that if you delete images with a FTP app, the gallery.txt will not be updated.

**Comment by GRMacGeek** [comment]
@jrondorf Oh I see now. I have to edit the gallery.txt file (delete all the entries) if I use FTP. So the issue really is that Pulse doesn't update the gallery.txt file if you use an FTP to upload multiple images, or delete any, you can only add or delete through the Pulse dashboard.

Just an FYI though if a user does delete images via FTP, and doesn't "fix" the gallery.txt file, the files will still show up in the Pulse dashboard, BUT you can't delete them... image attache showing this
![pulse_cms](https://user-images.githubusercontent.com/6706155/45958423-681dce80-bfe5-11e8-9798-adf1fafd6993.jpg)

**Comment by jrondorf** [comment]
Thanks therefore, a good find for Michael. 

I will provide a fix for Gallery Stack when I have returned, unfortunately this will be sometime end of October. Sorry for the inconvenience.

**Comment by ghost** [comment]
Thanks @GRMacGeek - somebody (maybe yourself?!) had reported this already by email and we have this noted. Most users edit via Media admin but we will add a failsafe for FTP changes also in a future update

**Comment by ghost** [comment]
This is now built and be in Pulse5.2B5 release (next release)
