### ISSUE TITLE
Pages getting stuck loading

### ISSUE THREAD

**Issue by GRMacGeek** [yuzoolcode/pulsecms-tracking#64]
May or may not be the right place

I am having really slow load issues with Pulse/Rapidweaver sites they are choking on this request 

pulse/admin/inc/tracker.php?uri=/pagename/&ref=none

for example this page https://www.weselldgs.com/about-us/  gets stuck here https://www.weselldgs.com/pulse/admin/inc/tracker.php?uri=/about-us/&ref=none takes on average 2 minutes to load, if it loads at all... 

and then moving between pages another 2 minutes per page...

**Comment by jrondorf** [comment]
Which GEO IP Setting are you using? -> Settings

**Comment by GRMacGeek** [comment]
Ohhhh! The GEO IP settings are messing it up! I unchecked it and all is good now, I have this problem on a bunch of sites, is it on by default? Or did I check it everywhere by accident?

**Comment by jrondorf** [comment]
Which GEO provider was active in your settings? It could be that one of them isn't working any more, which might be already has been corrected by Michael.

**Comment by jrondorf** [comment]
Yes, it's turned in by default I guess.

**Comment by ghost** [comment]
This is always the right place @GRMacGeek - thank you !

Yes it's on by default. Maybe we can switch it to off in the next update.
But yes, was it on and no API key inserted?

**Comment by GRMacGeek** [comment]
Yes it was on, and without an API key. The websites won't load for 2 plus minutes in some cases if it is on... Had to go through all the websites I had been upgrading and turn it off.

**Comment by ghost** [comment]
Thanks for the report

**Comment by ghost** [comment]
We've just removed the old default freegeoip since its now deprecated. 

But also the ipstack logic now skips the poll if the api key is missing so future installs or updates you won't need to go through your sites and do this @GRMacGeek 

Thanks for reporting. This is ready and will ship in next BETA soon
