### ISSUE TITLE
RecentPosts tag shows draft items

### ISSUE THREAD

**Issue by GRMacGeek** [yuzoolcode/pulsecms-tracking#68]
if you use the Recentposts tag, it will show all the blog items, including any "draft" items...

**Comment by ghost** [comment]
Good find @GRMacGeek  ^ thanks for the report

Just about to release 5.2 so this will have to come in 5.2.1

**Comment by ghost** [comment]
This is fixed and will ship in 5.2.2 :) 

Thanks @GRMacGeek
