### ISSUE TITLE
Pages of the block can not be chosen for the editor

### ISSUE THREAD

**Issue by ManuelRosique** [yuzoolcode/pulsecms-tracking#69]
Hello, in the configuration for the user-editor permission, and allow you to see / modify certain blocks, there is a block that does not appear, so that the editor can make changes eg 1 and 2.

- audios-mod
- manuales
- panel-de-instructores
- social-media
-versiones-anteriores

![1](https://user-images.githubusercontent.com/45614105/49486689-107db980-f805-11e8-8a5f-bbd7261952e6.png)
![2](https://user-images.githubusercontent.com/45614105/49486690-107db980-f805-11e8-839d-a73ec40f9b36.png)

they are in the block area perfectly, but to give access to the editor there is a block that does not appear ex. 3 and 4

![3](https://user-images.githubusercontent.com/45614105/49486691-107db980-f805-11e8-990d-d123b9052fa4.png)
![4](https://user-images.githubusercontent.com/45614105/49486692-107db980-f805-11e8-9d26-6596ca71833b.png)

Any suggestions for this setback
I am using the version of pulsecms 5.1 with blocsapp

**Comment by ghost** [comment]
Can I just clarify...?

So you are saying for example these two:

- audios-mod
- manuales

Are "not" highlighted in the settings but they are still appearing in the Editor's dashboard?

If so this is not expected behaviour. When you logout as Admin and login as Editor these should be disappeared. 

From testing this is working but we'll need to do more to confirm.

**Comment by ManuelRosique** [comment]
no, the block of previous versions, does not appear in the list to select for the editor! As shown in the image, the only block that does not appear is that of previous versions.

with reference to the block of audio-mod, it is not selected because pulsecms does not let me upload audio, I can not enable that block even until I can upload audios!

"versiones-anteriores" it is the only block that does not appear in the list, to select it and the editor can make adjustments!

**Comment by ghost** [comment]
Ok so this block: "versiones-anteriores"

- what's inside the block?
- how was the block created? 
- was it made different to all the others or made in the same way? (e.g. with Blocs app or with the Pulse backend Admin UI or on the server)...


> with reference to the block of audio-mod, it is not selected because pulsecms does not let me upload audio, I can not enable that block even until I can upload audios!

There is solution for that here #70

**Comment by ghost** [comment]
I just went into your install and created a new Block called "test" and pasted in the same content from "versiones-anteriores" and it appears

![2018-12-06 at 11 07](https://user-images.githubusercontent.com/4608547/49556503-707c7900-f947-11e8-9ccc-39f13bde7e75.jpg)

So I would either:

- delete "versiones-anteriores" and recreate it and see if it works
- Rename test.txt to another name and change it on your page and delete "versiones-anteriores"

Maybe second option will work best

**Comment by ManuelRosique** [comment]
all blocks are echoes in the same way, the notion is the same as the other blocks, using the blocsapp application, use pulsecms only for content management.

Within the block of "previous-versions" you only have one download file that will be attached every month

I saw that he made the change and deleted the content, no problem with reloading it! but it has not been created for the use of the editor

**Comment by ghost** [comment]
The "test" can be crated for the editor - please just check it in the settings as in the screenshot above.

Please rename test.txt to another name and change it on your page where you want it to appear and delete "versiones-anteriores" and this will work.

The error must have been creating that Block for some reason but re-creating it in Pulse will work.

**Comment by ManuelRosique** [comment]
I just did it, delete previous versions, and change the name, but it still does not appear for the editor !, and on the page it does not link to anything! I guess because you can not find the block with the link, it's very weird, is not it?

**Comment by ghost** [comment]
What new name did you use? Please use a completely new word :)

**Comment by ManuelRosique** [comment]
appears, but on the page it looks like this! What could it be that generates this?

![captura de pantalla 2018-12-05 a la s 8 51 40 p m](https://user-images.githubusercontent.com/45614105/49558148-ab42ca80-f8cf-11e8-82ed-0c33cf9c27cc.png)

**Comment by ghost** [comment]
That means that Block is missing...

So in the "Page" inside Pulse (go to that Page folder) change the Block name that is on that page from "versiones-anteriores" to your new Block name

**Comment by ManuelRosique** [comment]
in pages there is no previous one, everything is inside the page of instructors do not know if what I have to change is this inside the page?

![captura de pantalla 2018-12-05 a la s 8 58 17 p m](https://user-images.githubusercontent.com/45614105/49558398-8569f580-f8d0-11e8-8d67-a1aa67dba65c.png)

**Comment by ManuelRosique** [comment]
I tried to change the name of "previous versions" found in the instructors page, but it does not let me save, so what I'm going to do is change the name in the blocsapp file and upload it again I think it can work in that way

**Comment by ghost** [comment]
Ok sounds good

For reference it's the {{block:versiones-anteriores}} to change to {{block:new-name}}

**Comment by ManuelRosique** [comment]
perfect! change the name solve the problem!

**Comment by ghost** [comment]
Great!
