### ISSUE TITLE
Creating a new Folder in Pages breaks on some installs

### ISSUE THREAD

**Issue by ghost** [yuzoolcode/pulsecms-tracking#71]
> The problem appears after creating sub-folders under "PAGES" on the live server. As soon as the folder is created the "PAGES" section of the Admin does not work. In fact it is weird.
> 
> The source code produced upon returning to "PAGES" is as follows:
> <div class='breadcrumb'>
>                 <a href="http:///pulse-5.2/">Home</a> » <a href="http:///pulse-5.2/admin">Admin</a> » <a href="http:///pulse-5.2/admin/index.php?f=pages">Pages</a>                   </div>
>         <div class="view-helper-pagination"><ul><li><a class="older" href="?f=pages&pnum=1">1</a></li>
> </ul></div>
>

**Comment by todotermas** [comment]
PLEASE, MY SERVER WALKS OK. SEE YOUR SERVER HERE >>> https://5demo.pulsecms.com/

SEE IN PAGES THE ERROR OF DIRECTORY. REGARDS

**Comment by ghost** [comment]
Thanks @todotermas we are investigating and will get back to you with a solution soon

**Comment by ghost** [comment]
This is a very strange bug @todotermas . There is a page file in your site with no .txt extension. So the existing coder errors out.

How thats happening is a mystery. We've tested the page/folder creation and the submit event handler adds the extension as needed.

So its either JS turned off, the submit handler not firing in time (might be browser related) or the file might be added manually.

As a fix we've added some code to detect and then skip these files for the next release. Its a really strange bug.

**Comment by ghost** [comment]
Apparently everything works Ok after this patch in next BETA

**Comment by ghost** [comment]
5.2.2 will be out in the first few days of January and this fix is included :)
