### ISSUE TITLE
blocks content not refreshing on output

### ISSUE THREAD

**Issue by pulsecmsuser** [yuzoolcode/pulsecms-tracking#73]
running latest pulse release. i can add and edit blocks in pulse admin. but, when i call that content via a Embed URL: or Embed HTML: link, it always shows the original added content but doesn't refresh to ever display the edited content,

for example: if i create a new block called test and add content to it that says "test content v1",  i can output that content via an Embed URL: or Embed HTML and see it. But, if i go back into admin and change the content to "test content v2" and i view the Embed URL: or Embed HTML., it still shows "test content v1", even though admin is showing "test content v2".

**Comment by ghost** [comment]
Thanks and we will test this use case

**Comment by pulsecmsuser** [comment]
thanks! actually -- it looks like the changes in admin do eventually show up... the content changes just take a long time to appear. maybe it is just something to do with cache times? is there a cache refresh time setting in pulse and/or, which other cache setting(s) on the web server/in php would need to be changed if this is indeed the case? thanks again!

**Comment by ghost** [comment]
Ah yes the cache! You are right. You can switch the cache off in settings then it will load instantly.
Admin > Settings after logged in. Can you switch it off and test? (clear browser cache after switching off).

There's no need to set anything on your server but if you have a cache on or using something like Cloudflare then yes this will need to be off too.

**Comment by pulsecmsuser** [comment]
That cache setting was already disabled by default. I even enabled it and disabled it again to see if the setting took. But, it is still not refreshing.

 

I don’t use any other cache server/provider. Any chance some caching is on is apache /php I could look at that may need changed/disabled?

**Comment by ghost** [comment]
> That cache setting was already disabled by default. I even enabled it and disabled it again to see if the setting took. But, it is still not refreshing.

What browser are you using? You may need to clear the browser cache or check that is off.

> I don’t use any other cache server/provider. Any chance some caching is on is apache /php I could look at that may need changed/disabled?

That depends on your host. Who are you hosting with? Could you ask them about this?

We will test this also

**Comment by pulsecmsuser** [comment]
Tried the latest ie, firefox, edge, and chrome on win10 64bit – all have the slow to display content refresh issue.

 

SO – I really think it is a server-side (either pulse or php or apache) problem. The host is hostek.com. I’m not paying for any specific caching service and I can’t find any enabled caching settings in cpanel to disable. I’ll call and ask them and report back…

**Comment by pulsecmsuser** [comment]
Called provider/hostek.com. They don’t think they have any cache engine running by default on the server. PHP is 7.2. A php_info output reveals all caching to be off.

 

I have changed the content of a block in admin AND even edited end_point.php with some comments, just to change the size and date of the files.

 

Again, my changes are instantaneous in pules admin. The block content text file change in instantaneous. BUT, the block embed via 

<?php readfile('https://fmcw.info/learn/end_point.php?item=blocks%2Ftest1'); ?>

 

Doesn’t refresh. It still shows the original value of the block content text file rather than the new version(s) I keep modifying successfully in admin.

**Comment by ghost** [comment]
With blocks not refreshing - think it is the cache settings on server

However, we have added fix for the cache to do extra clearing on the open page as a precaution 
This will be in the next update (5.2.2) shipping later this month/early Jan

**Comment by ghost** [comment]
5.2.2 will be out in the first few days of January and this fix is included :)
