### ISSUE TITLE
"Preview" links point to wrong URL

### ISSUE THREAD

**Issue by GRMacGeek** [yuzoolcode/pulsecms-tracking#75]
Two "Preview" link issues (At least in Rapidweaver/Pulse)

1. The "Preview" link in the "Account" menu doesn't link to the right place - it adds /pulse to the URL
2. The "Preview" button in the blog post menu also goes to the wrong place, not pointing to the proper URL

Images attached below.
![preview-screenshot-pulse-cms](https://user-images.githubusercontent.com/6706155/50014884-30467780-ff93-11e8-92d6-ede9dd1d750a.jpg)
![blog-screenshot-pulse-cms](https://user-images.githubusercontent.com/6706155/50014892-34729500-ff93-11e8-96d1-843f0051c10e.jpg)

**Comment by ghost** [comment]
Thanks @GRMacGeek for reporting this in. This is an outstanding issue we are trying to deal with in this integration. The solution might be to allow users to hide preview for their sites.

- The top right drop down cannot be fixed at the moment - but it does work in Pulse vanilla. Just not in Pulse+RW at the moment. But we'll keep thinking on this.
- This should be working if the URL for the blog is set correctly in Admin > Settings under Blog/RSS section.

**Comment by ghost** [comment]
Ref:
https://forum.pulsecms.com/t/preview-in-admin-panel-goes-to-wrong-folder/1231/4

**Comment by ghost** [comment]
Fixed in 5.3.8
