### ISSUE TITLE
P5 navigation stack

### ISSUE THREAD

**Issue by jrondorf** [yuzoolcode/pulsecms-tracking#76]
From @GRMacGeek

> I have been playing with the new “P5 Navigation stack”. Looks good so far, but having trouble on some themes, when trying to use a “fixed menu”, it is leaving a “gap” on the left side of the main body container. (Screen capture attached)
> 
> It works with some themes like Foundry (goes all the way across the top) but not with themes like Foundation or your Blankstrap theme.
> 
> btw this problem also exists with Yuzools Navigation stack as well. There are a few of his stacks that don’t play well with themes like Foundation…

![pulse-menustack](https://user-images.githubusercontent.com/2099795/50519942-99fb7100-0abd-11e9-9bf6-1749ffe89577.jpg)

**Comment by jrondorf** [comment]
@yuzoolcode Maybe best to fix this in the original Navigation Stack and then port the changes to the P5 Navigation Stack also?

**Comment by ghost** [comment]
Thanks @jrondorf 

Works fine in Foundation with RW8 + Navigation Stack (not testing with P5 Navigation Stack here):

![2018-12-30 at 19 45](https://user-images.githubusercontent.com/4608547/50546491-c05f0f00-0c6b-11e9-96a1-5ab5b5af3471.jpeg)
![2018-12-30 at 19 46sd](https://user-images.githubusercontent.com/4608547/50546492-c05f0f00-0c6b-11e9-8243-d834882d926e.jpeg)
![sfd](https://user-images.githubusercontent.com/4608547/50546526-306d9500-0c6c-11e9-9d85-35303e1ece29.jpeg)


@GRMacGeek: can we replicate this in Foundation + Navigation Stack firstly to narrow the problem?

**Comment by GRMacGeek** [comment]
Weird... I had tried both stacks (Yuzool Nav and P5 Nav) on a couple of Foundation projects, and had that strange gap (the pic is from a Foundation test project) Tried it this morning and suddenly it is working with both stacks... The only thing that is not working is the Yuzool Nav "Start Content Below Navigation" setting when I am in foundation. End up having to use a "spacer stack"

- however "gap" issue does still exist (at least for me) when I try to use either stack on Instacks "Blankstrap" theme, and a different "gap issue" in the "Void" theme. 
- issue also exists with Themeflood "RW Skinz" (at least the demo, I don't own the stack set) and his "Bootstrap" theme as well

I have been trying to find a "blank Rapidweaver theme" or at least a "minimal" one as a starting point to projects... preferably one that is Bootstrap based as well, and plays nice with Pulse. Looking for less overhead on page loads... (speed baby, speed!) If only Blocs3 played better with Pulse... The first site I built with it is the fastest loading site I have ever built, scoring 100 on Pagespeed insights, and I haven't even started some of the normal optimizations yet... But the Pulse integration doesn't work...

**Comment by jrondorf** [comment]
Please send me your blankstrap project with the navigation stack embedded, where this gap occurs, I will check. Thanks!

Also with the Void theme :-)

**Comment by GRMacGeek** [comment]
- [here is a link](https://dsc.cloud/Raimo/nav-stacks-blankstrap.zip) to the "Blankstrap" project with 2 pages, one with Yuzool Nav, the other with P5 Nav
- [here is a link](https://dsc.cloud/Raimo/nav-stacks-void.zip) to the "Void" project also with 2 pages. For this one notice the smaller space to the left and above the nav

**Comment by jrondorf** [comment]
For Void, I just released an update ro remove the margin generated by the browser. Check the auto updater.

For Blankstrap, set the Content Container to None. If you need containers on the stacks page, use the container stack. Download the repository to get the stacks: https://github.com/inStacks/Blankstrap

I guess something like this is also the case in Foundation.

![2018-12-30_23-36-56](https://user-images.githubusercontent.com/2099795/50552093-530fa600-0c8c-11e9-8dfc-1310832c595d.png)

**Comment by GRMacGeek** [comment]
And that fixes it for these 2! Thanks! Blankstrap just became my "template theme" for Rapidweaver.

**Comment by jrondorf** [comment]
Great to hear 👍
