### ISSUE TITLE
Menu in Pulse 5.2.2

### ISSUE THREAD

**Issue by IvaRoSoft** [yuzoolcode/pulsecms-tracking#77]
When creating a dialectical page for example: "Úvod2".
The menu will appear as "Vod2".
HTML5 entity, is currently also a bad solution

In the Page Folder, create a "mysample" folder.
In the folder "mysample" create Page "sample1".
The menu will show "Mysample Sample1"
The text in the menu of "Mysample". It is redundant text.

(Link to special characters: [it's here](https://www.quackit.com/html/html_editors/scratchpad/?app=charset_ref&entity=Uacute&hexadecimal=000DA&decimal=218))

![pulse522-menu](https://user-images.githubusercontent.com/29908185/50695382-bf97f580-103c-11e9-8572-a3ea3fb11cb7.png)

Code:pulsecore/storage/config.json
`"navigation": {
        "all": {
            "&Uacute;vod2": {
                "url": "\/uvod2",
                "active": true
            },
            "&#218;vod": {
                "url": "\/uvod",
                "active": true
            },
            "mysample\/sample1": {
                "url": "\/mysample\/sample1",
                "active": true
            },
            "about": {
                "url": "\/about",
                "active": true
            },`

**Comment by ghost** [comment]
Thanks - this needs testing and fixing, thanks for the report

**Comment by IvaRoSoft** [comment]
I apologise!
I'm absolutely forgetful about it,
do not write script names in the dialetry.
Adjusting the menu, I have already commented on the forum.
It is best to create an editing field to change the name.
You will need to edit script "\pulsecore\filter.php"
to accept all the languages in the pulse.

You may need to create a new field for config.json
Example:
```
    "navigation": 
    {"all": { 
    "\u00davod": { 
    "url": "\/uvod", 
    "active": true
    "name": "\u00davod" },
```
  "name" It can be used for breadcrumb.

**Comment by ghost** [comment]
Thanks @IvaRoSoft  - I see it is written here:
https://forum.pulsecms.com/t/no-special-characters-in-the-menu-items/1241/7

Does that mean we can close this issue and that is the solution?

**Comment by IvaRoSoft** [comment]
You can close.
