### ISSUE TITLE
Mailchimp

### ISSUE THREAD

**Issue by IvaRoSoft** [yuzoolcode/pulsecms-tracking#78]
Mailchimp (and other non-translated, tags / plugins ==?)
mailchimp.php
Translate languages:
- label, line 16
- placeholder, line 17
input value, line 20

**Comment by ghost** [comment]
Good enhancement idea

**Comment by ghost** [comment]
Add Mailchimp lang settings and other tags for 5.2.3

**Comment by ghost** [comment]
Done:
https://github.com/yuzoolcode/pulsecms-languages/commit/d1e78b3c9f7d7461a18c5690e227ef3332a86dcd
