### ISSUE TITLE
Font Awesome

### ISSUE THREAD

**Issue by IvaRoSoft** [yuzoolcode/pulsecms-tracking#79]
mishmash Font Awesome:
admin = Font Awesome 4.7.0
template = Font Awesome v5.2.0

For proper view in block editing

**Comment by ghost** [comment]
Good find, thanks

**Comment by ghost** [comment]
Updated Font Awesome so now in sync. Backend and Default demo now both run off 5.2.0 with admin using local SVGs added also

This is in 5.2.3 out in next version
