### ISSUE TITLE
Pulse - help.

### ISSUE THREAD

**Issue by IvaRoSoft** [yuzoolcode/pulsecms-tracking#80]
Update all links on your page and in .pdf files.
(Https://www.pulsecms.com/help/article/10-version-history). ???
In the .pdf file, give specific examples of usage and setup (2/3).
For example:
- admin settings manage_tags - Manage the tags
(use, example).

**Comment by ghost** [comment]
Thanks - these are just simple / quick docs

The details seem to need to go in the manual

**Comment by ghost** [comment]
This is a work in progress and help and manual always being updated as much as possible.
Closing this for now as it is constantly evolving. Will bear in mind adding more examples.

And if others wanted to contribute we could make a formalised Wiki on top of the forum?

**Comment by IvaRoSoft** [comment]
"And if others wanted to contribute we could make a formalised Wiki on top of the forum?"
This is an excellent idea!
Fast to work, still today.

**Comment by ghost** [comment]
Thanks - not sure when we can do it, but let's think about it
