### ISSUE TITLE
Pulse-backup-mail.

### ISSUE THREAD

**Issue by IvaRoSoft** [yuzoolcode/pulsecms-tracking#81]
Example: The webmaster has 5 servers, modifies each server and receives backup emails.

![mail-backup](https://user-images.githubusercontent.com/29908185/50698205-9a0eea00-1044-11e9-8766-6861e54c8745.png)

Sender: Root User (script: PHPMailer.php, line 83)
Subject: Incorrect text (script: auto_backup.php, line 166)
Possible solution:
Root User = server name.
Subject = UTF_8. ???

**Comment by ghost** [comment]
Thanks - will test and fix

**Comment by ghost** [comment]
This is fixed:
UTF-8 in the backup e-mail fixed

Will be in 5.2.3
