### ISSUE TITLE
Breadcrumb local habits.

### ISSUE THREAD

**Issue by IvaRoSoft** [yuzoolcode/pulsecms-tracking#82]
It is necessary to adapt breadcrumb to local habits.

Proper display name of "Home" in Slovak
Example: Page Name is "Home" = "Úvod" or "Domov"

Proper display name of "Home" in German
Example: Page Name is "Home" = "Startseite" or "Hauptseite"

Russian:
Proper display name of "Home" in Russian
Example: Page Name is "Home" = "Главная" (Glavnaja)

````

// Nev definet admin settings mybreadcrumbhome
// sample Russian
$mybreadcrumbhome = "Главная";

// \pulsecore\tags\breadcrumb.php r. 25
$crumbs = array(
$mybreadcrumbhome => ($GLOBALS['path'] . '/'),
);

// If admin setings: Blog URL prefix: news
// \pulsecore\tags\breadcrumb.php
// replce all string "blog" to setings:"url_prefix"
//----------
// Replace the expression behind the separator 
// as shown in the active menu, after renaming the page
// example:
// Home >> as shown in the active menu
//----------
// Add a new entry to the right.
// echo $page_title
```
`

**Comment by ghost** [comment]
This is added in version 5.2.3
"Breadcrumbs are now localised"

**Comment by ghost** [comment]
Done:
https://github.com/yuzoolcode/pulsecms-languages/commit/4a8304f75c5c6ea1b4eb0d32cb071533e29d115a
