### ISSUE TITLE
Install page - Local customs

### ISSUE THREAD

**Issue by IvaRoSoft** [yuzoolcode/pulsecms-tracking#83]
It is necessary to adapt the introductory page with local customs.
```

// Nev definet admin settings myhomepage
// sample Russian
$myhomepage = "glavnaja";

// index.php r. 178
if (preg_match("/\//", $page)){
if(file_exists("content/pages/".$page.$myhomepage.".txt")){
    $page = $page.$myhomepage;}
} else {
    if(file_exists("content/pages/".$page."home.txt")){
        $page = $page."home";
    } 
}

// index.php r. 43 "home" = ???

```

**Comment by ghost** [comment]
I'm not sure this is necessary. This is for the demo content or in the dashboard?

**Comment by IvaRoSoft** [comment]
This is Pulse installation, index.php.
You need to add the settings to the admin panel's settings.
.............

**Comment by ghost** [comment]
We've not had a request to translate the install page. This is a good idea so will consider it for a future update.

**Comment by IvaRoSoft** [comment]
I mean the index.php opening page.
Where the "home" text adapts to the Admin panel settings.
An example for Slovak.
Administrator panel setting is "domov".
Always the home page opens "domov".
This also applies to the breadcrumb.

**Comment by ghost** [comment]
I'm really sorry @IvaRoSoft but I don't understand this feature request 😣

- Do you mean change this just to adapt the word "home"?
- to offer local translations of Home content just use the "{{localizer}}" tag

**Comment by IvaRoSoft** [comment]
This is an option in Administrator.
Which page appears as the first page instead of the "home" page.

**Comment by ghost** [comment]
- This is added as an option in the next update (5.2.3)
- Allow other pages than home to be used via Settings in Admin
- Create a page with the title you want
- Select it in the settings and it will be the new Home

**Comment by ghost** [comment]
Lang settings for this option:
https://github.com/yuzoolcode/pulsecms-languages/commit/adca8eb296c830d4afd920c95adb2ed267335b0a
