### ISSUE TITLE
User profile issues...

### ISSUE THREAD

**Issue by ralphlambiase** [yuzoolcode/pulsecms-tracking#85]
So I created a user group, then a user. I logged out of the Admin profile and logged into said "User" ("adrienne") from the drop-down menu on the login screen. Upon trying to log out using the drop-down menu "logout", the page simply refreshes leaving me logged in under the same "User" ("adrienne")... Plus, locked in under this profile, I can't access any log files.

**Comment by ralphlambiase** [comment]
So after about an hour of first encountering this issue, I tried the logout button from the drop-down menu again and TA DAHHH! It worked! That was truly strange...

**Comment by ralphlambiase** [comment]
Ok, now we have another issue. I logged back in as the administrator and changed the generic password to something more secure. I then changed the setting of "Navigation > Enable frontend editing>" from "Admin and Editor" to just "Admin". I log out and find that my new User which I created ("adrienne") has disappeared from the drop-down menu on the Front End login page. It is only showing me "administrator" and "editor" in the list. Also, the User Group has also been automatically deleted by this action.

Maybe a warning needs to be in place to let people know that the defined User "adrienne" will be deleted. Another question (since Editor is NOT enabled in my settings): Why is there an editor name listed in the drop-down selector at all? Seems that there shouldn't be an option for the generic editor profile. Maybe streamline all the Users (admin, editor, and users) into one cohesive page?

**Comment by ghost** [comment]
Thanks @ralphlambiase  - we'll take another look at these.

It's possible to amend the Editor from the dropdown as you say and possibly add a warning before deleting. We're working on 5.2.3 at the moment and will consider this for that update or just beyond. Will update here soon.

**Comment by ghost** [comment]
Thanks @ralphlambiase 

This has been fixed for the coming update:

>  Another question (since Editor is NOT enabled in my settings): Why is there an editor name listed in the drop-down selector at all?

It now won't appear.

--

It might be worth merging all the user management into a unified block, but that will be a huge change with all sorts of ripple effects. Maybe leave that for another day.

In the meantime the way to manage them all is from the Settings sub Pages screen. Deleting a user/group should be self-evident but will add more notes on that also. 

Thanks for your help with this issue!
