### ISSUE TITLE
Inline Editor doesn't work with Blocs

### ISSUE THREAD

**Issue by GRMacGeek** [yuzoolcode/pulsecms-tracking#86]
Pulse Inline editor is not working with Blocs 3 generated files

Test site here - [http://www.pmengraving.net/test/](http://www.pmengraving.net/test/)

css conflict maybe?

Blocs generated "Pulse 5" files [here](https://dsc.cloud/Raimo/PME-PM-Engraving-pulse.zip)

**Comment by ghost** [comment]
Thanks for sending those. Please try replacing the layout.php with this and see if it helps?

[layout.php.zip](https://github.com/yuzoolcode/pulsecms-tracking/files/2764319/layout.php.zip)

**Comment by GRMacGeek** [comment]
Getting closer. Menu now appears, but no "inline editor" pic attached
![pm_engraving](https://user-images.githubusercontent.com/6706155/51253472-65683000-196c-11e9-8fcb-1d62ab4c5fcb.jpg)

**Comment by ghost** [comment]
Thanks - can you share the demo site login for a few more checks?

**Comment by GRMacGeek** [comment]
Absolutely! Emailing you the password at support@pulsecms.com right now

**Comment by ghost** [comment]
Could you also DM it to me on the forum too? Thanks
This might take a few days to find the problem and will have to get the exporter in Blocs app amended also

**Comment by GRMacGeek** [comment]
Done.

Let me know if you need anything else. I did open a "bug report" over at Blocs as well. Will you be in contact with Norm over there, or should I report that you are also working on it?

Also - I will be making this site "live" on the main URL today, but will leave the "test" link up for you to play with

**Comment by ghost** [comment]
Thanks for leaving the test and bug report - will also be in touch with Norm too - thanks :)

**Comment by ghost** [comment]
Have narrowed this down and a fix for the exporter should be in the near future :)

**Comment by cazoobi** [comment]
Blocs 3.1.1 includes the fixes for the inline editor.

**Comment by ghost** [comment]
Wahoo thanks @cazoobi  - this is cool 🤩
