### ISSUE TITLE
Tag navigation

### ISSUE THREAD

**Issue by IvaRoSoft** [yuzoolcode/pulsecms-tracking#88]
Navigation tag {{navigation}}
create the html code: 
```
<div id="nav" class="all">
```
Example css
```
/* 2.1: Main menu */
#nav { ... }
```
????????????

You are talking about Pulse like Bootstrap 4 ..
How to edit a tag {{navigation}}
to suit for Bootstrap 4
for example:
```
<div class="collapse navbar-collapse" id="navbarSupportedContent">
```
You must add optional "class" and "id" extensions.

**Comment by ghost** [comment]
There are also situations when templates are not using Bootstrap that may only want `id="nav"` and can style their menu bars with this.

So will have to think how best to proceed on this..

**Comment by IvaRoSoft** [comment]
It is right to think for multiple use.
In the forum I mentioned this problem.
I've included two examples of how to insert a tag in the navbar.
It works quite well.
However, it is necessary to modify the code js.
I'm trying to complete this example, I need help

**Comment by ghost** [comment]
@IvaRo do we close the issue now and continue on the forum?

**Comment by IvaRoSoft** [comment]
Yes, we can close.

**Comment by ghost** [comment]
This has been added to the code base for 5.2.3 :)
