### ISSUE TITLE
help with file upload problem (old problem)

### ISSUE THREAD

**Issue by ManuelRosique** [yuzoolcode/pulsecms-tracking#89]
I am having anomalies to upload files in the multimedia area, either JPGE, PDF or ZIP.

When I upload a larger file, (1.5 MB for example), the pulse seems to process it, and the load icon becomes the "checkmark". Everything seems fine, but the file is not in view.

this problem had already been solved with the host configuration, but it has reappeared, I have reviewed the hosting configuration, but it is still intact, it is still the same.

I had already asked about this problem, but it keeps popping up every time! I'm using version 5.1

**Comment by ghost** [comment]
Please could you review the solution in the past post:
https://github.com/yuzoolcode/pulsecms-tracking/issues/70

The upload is fine in testing so the question is why was it working and now stopped working?

- did you update pulse?
- did the host change anything?

**Comment by ManuelRosique** [comment]
I still do not understand why it does not work,

the .htaccess is correctly fine, and POST_MAX_FILESIZE and UPLOAD_MAX_FILESIZE are correctly configured, I have not updated pulcecms, but I can not upload files! Is there any way they can review it? or some idea of ​​what it could be? Is it useful if I record how I upload the file? Mark the arrow up, but when looking in the folder is not found!

**Comment by ghost** [comment]
To help narrow this down:

- this was fixed before (
https://github.com/yuzoolcode/pulsecms-tracking/issues/70) so something must have changed
- did you update pulse? Sounds like not
- did the host change anything? Ask them
- can you update Pulse then to the latest version (5.2.2)?
- what do your logs say? Please attach the logs from settings>extend>logs

**Comment by ManuelRosique** [comment]
Hello, answering your points:

Not that it was fixed, I still can not upload mp3s and files larger than 2mgs, now I have not been able to upload files from greater than 1MG from pulsecms

I have not updated pulsecms

Specifically, what would you have to ask the hosting support service you hire? to make the result faster!

Blocsapp has not released the integration update with the application so I have not been able to update it, I do not want to risk the beta version you are using! but I will ask about this action could it be that this solves the problem, or maybe not!

I have reviewed the record after uploading a file, and it does not appear in multimedia, I have gone to register but it does not say any related to that

--------------------------------------

I am currently uploading everything via FTP, but I am looking for the client to make the changes from pulsecms, the only thing I need is that you can upload bigger files and upload mp3 files!

I remember that once I worked with the settings that you gave me in configuration, and then I stop working! and I have not found a way to make it work again! It's very strange

try to upload a file at this time and this is what marks the record, nothing was raised in the area of ​​multimedia
![captura de pantalla 2019-01-30 a la s 9 43 19 p m](https://user-images.githubusercontent.com/45614105/52029285-314a4e80-24d8-11e9-9d83-94bc01935311.png)

**Comment by ghost** [comment]
- I think the upload error is around the list of allowed file types in the config/settings. 
- The upload size problem sounds like the .htaccess (or php.ini) needs to be modified to change the upload_max_filesize and post_max_size. 

----

So:

1. Have you allowed the right file types in settings?
2. Have you changed the htaccess to allow upload_max_filesize and post_max_size?
3. Have you also changed php.ini to allow upload_max_filesize and post_max_size?

If the server upgrade your PHP version it might override number 3.

**Comment by ManuelRosique** [comment]
the php.ini file I've never used, I'll give it a look

**Comment by ManuelRosique** [comment]
upload_max_filesize   100M
post_max_size             128M

htaccess y php.ini It has the same configuration in both cases, and if I have knowledge to upload all kinds of files..
![captura de pantalla 2019-02-03 a la s 3 33 59 p m](https://user-images.githubusercontent.com/45614105/52183004-330e5d80-27c9-11e9-9967-3accbaa1b3c7.png)

**Comment by ghost** [comment]
- so this means the upload has never worked for you before?
- Or did it work and then it "stopped" working?

- Maybe send us your site and SFTP/FTP details via the forum in a private message and we can take a look. 
- If there's nothing obvious then it's a server setting as this works in testing

**Comment by ManuelRosique** [comment]
yes, indeed once worked correctly, and out of nowhere I stop working!

**Comment by ManuelRosique** [comment]
As I sent you a private message through this forum, I can not find the option

or sent it to the pulsecms mail?

**Comment by ghost** [comment]
- if it stopped working out of nowhere I really think you have to contact the hosts. They might have updated something on the server that we don't know about. Have you contacted them yet?
- send me through the Pulse forum: https://forum.pulsecms.com/latest 
what is your username on there?

**Comment by ManuelRosique** [comment]
I have not yet contacted him, take a look! to discard any doubt, I send you the data, although in the past I already sent it to you once! I think I'll send them back! Thanks for the attention

**Comment by ghost** [comment]
- thanks please send them in the forum as we would have discarded from before for security 
- and please contact the host also :)

**Comment by ManuelRosique** [comment]
Hi, could you check the pulsecms system? Thanks in advance

**Comment by ghost** [comment]
- what did the host say?
- our tests show it's working :)

**Comment by ManuelRosique** [comment]
I am currently testing pulsecms on another hosting with the new version, but at the moment of entering the editor, the page remains blank: S is worth mentioning that I'm still using blocsapp but this is another case of error, which never ends
