### ISSUE TITLE
Can't create a second/new blog

### ISSUE THREAD

**Issue by oliver-77** [yuzoolcode/pulsecms-tracking#9]
When trying to create a second/new blog page, the content is not rendered in the frontend.

1. Creating a new blog page under blog
![bild 002](https://user-images.githubusercontent.com/24696577/33873592-e118c1a6-df1b-11e7-8129-ccc523b6ac71.png)

2. Adding some dummy content inside the new blogfolder (newblog)
![bild 12](https://user-images.githubusercontent.com/24696577/33873644-1d5b6ea2-df1c-11e7-9a4c-c477db9a3c4a.png)

3. Creating a new page (newblogpage)
![bild 003](https://user-images.githubusercontent.com/24696577/33873687-48900290-df1c-11e7-8024-9491d3def17a.png)

4. Adding the loop to this page
![bild 006](https://user-images.githubusercontent.com/24696577/33873706-5c429b7c-df1c-11e7-81fa-7d3870a04097.png)

When you now try to open the newly created blog it just shows the unrendered blog loop
![bild 007](https://user-images.githubusercontent.com/24696577/33873767-93abaf4a-df1c-11e7-893f-80006c0ac4a4.png)

**Comment by ghost** [comment]
@oliver-77 - just testing this (working on 5.0.2 updates):

Tags need to be in one line so no newlines after {{ or before }}
Could you try that again and confirm?

Thanks

**Comment by oliver-77** [comment]
@yuzoolcode - just tried it without a line break, here I get an Error 500.
Output from my local Dev machine (It looks the same on my real server):

`
Fatal error: Uncaught LogicException: A pre-condition has failed in D:\UniServerZ\www\pulse52\pulsecore\dbc.php:12 Stack trace: #0 D:\UniServerZ\www\pulse52\pulsecore\dbc.php(44): pulsecore\invariant(false, 'A pre-condition...') #1 D:\UniServerZ\www\pulse52\pulsecore\tags\blog.php(23): pulsecore\pre_condition(false) #2 D:\UniServerZ\www\pulse52\inc\tags\blog-show.php(67): pulsecore\tags\Blog->generate_html(Array, Array) #3 D:\UniServerZ\www\pulse52\inc\tags\blog-show.php(151): tag_blog_show(Array) #4 D:\UniServerZ\www\pulse52\index.php(275): include('D:\\UniServerZ\\w...') #5 {main} thrown in D:\UniServerZ\www\pulse52\pulsecore\dbc.php on line 12`

**Comment by ghost** [comment]
Thanks - will check

**Comment by ghost** [comment]
I think its missing the blog prefix parameter (the second one):

`{{blog-show:"newblog":"blog":"[[featured-image]] [[blog-content-loop(<<blog-item-author>> <<blog-item-date>> <<blog-item-featured-image>> <<blog-item-content>> <<blog-item-tag>>)]]"}}
`

So the blog prefix here is "blog"

Let me know if that works or not @oliver-77 :)

**Comment by oliver-77** [comment]
Works! Thanks! Except the order like in the main blog ;-)

Maybe this needs a little change to the Pulse Manual (Page 21)

**Comment by ghost** [comment]
Yes - the order bug will be fixed in 5.0.2:
https://github.com/yuzoolcode/pulsecms-tracking/issues/11

Have amended manual for this tag
