### ISSUE TITLE
Blog "back button" makes no sense

### ISSUE THREAD

**Issue by oliver-77** [yuzoolcode/pulsecms-tracking#90]
Hi,
what was wrong with my javascript solution? [https://forum.pulsecms.com/t/back-button-in-blog-posts/497](url)

The current button (Pulse 5.2.2) makes no sense for me if you are for example on page 2 or higher in the blog. I always get into the root directory of the blog.
I am wrong, have I missed something?

![back](https://user-images.githubusercontent.com/24696577/53336250-1237b480-38fe-11e9-8641-327f21a03eaa.png)

**Comment by ghost** [comment]
There were some bugs in 5.0.3 with the linking, so had to be improved for 5.1

See:
https://github.com/yuzoolcode/pulsecms-tracking/issues/25

But can look at this again and see what is going on

**Comment by oliver-77** [comment]
Okay, I get it. I didn't notice because I never use this search. ;-)
That should be a general problem because the data is not cached.

By the way: The search does not work with Pulse installations in subfolders, there is a / missing in the URL.

**Comment by ghost** [comment]
Sounds like the back button should be pagination aware - we can look at updating this.

> By the way: The search does not work with Pulse installations in subfolders, there is a / missing in the URL.

That looks like a separate issue so opening a new one for that: #92

**Comment by ghost** [comment]
Have updated this.

It will be out in the next update:

"Check back button solution doesn’t always go to root (from page 2 of Blog for example). Use referrer if it exists"

Thanks for reporting!
