### ISSUE TITLE
Renaming media

### ISSUE THREAD

**Issue by oliver-77** [yuzoolcode/pulsecms-tracking#91]
Hi,
when i try to rename something in the media, the path is appended to the filename and ends up in the root directory of media.

![bild 002](https://user-images.githubusercontent.com/24696577/53337523-f9310280-3901-11e9-9de3-d47cb6fa9aca.png)
![bild 003](https://user-images.githubusercontent.com/24696577/53337529-fafac600-3901-11e9-9cb7-75dc74343b38.png)
![bild 004](https://user-images.githubusercontent.com/24696577/53337533-fdf5b680-3901-11e9-9788-62f729bc0b55.png)

**Comment by AceTutor** [comment]
I concur with Oliver's conclusions - the rename function fails when used for pages, blocks and media when contained in a sub-folder.

I hope that this can be resolved to be included in version 5.3.

### Commendation:
Michael - Can I recommend that as soon as you are able to resolve issues listed here or on the forum that you supply a patch that we can use so we don't have to wait till the next version release.

_This is such a brilliant package and my clients really appreciate the ease to using Pulse. The word is spreading! Cheers!_

**Comment by ghost** [comment]
Thanks @AceTutor - it does looks strange. Needs a proper test. It might be around the filtering change. 
This will most likely ship in 5.3.1 (soon after 5.3) as 5.3 is ready for release for next week 🤩

We are trying to release as quick as we can, it just takes time with debugging and packaging but will get updates out faster. 

> This is such a brilliant package and my clients really appreciate the ease to using Pulse. The word is spreading! Cheers!

Thank you and glad you think so! 😍

**Comment by ghost** [comment]
This was a filtering bug - fixed for next release (hopefully end of next week)
