### ISSUE TITLE
Feature Request: Adding d.m.Y to the bootstrap.php

### ISSUE THREAD

**Issue by oliver-77** [yuzoolcode/pulsecms-tracking#93]
Hi Michael,
could you please add "d.m.Y" to the bootstrap.php maybe instead of d-m-Y.
This would be the correct german date format. 

Another possibility would be a free form field like in the past, (Settings -> Blog)
then the user can choose the date format by himself.

![date](https://user-images.githubusercontent.com/24696577/53548877-f537f700-3b32-11e9-86c7-a863ddabc782.png)

**Comment by ghost** [comment]
- We can add d.m.Y also - sure
- An option for free form is a good idea too but obviously these are in there to make it as user friendly as possible

**Comment by oliver-77** [comment]
Thanks! 👍

**Comment by ghost** [comment]
Have done a partial fix for this.

Added d.m.y in the options. 

Work in progress

**Comment by ghost** [comment]
Adding d.m.Y and free form option to the date settings ..
turned the date field into a textbox and added a datalist. 
The old select has been removed

This is ready for 5.3.2
