### ISSUE TITLE
Feature Request: Replacing the Dropdown field at Pulse Login

### ISSUE THREAD

**Issue by oliver-77** [yuzoolcode/pulsecms-tracking#94]
For security reasons I would replace the drop down menu with a simple text field.
Due to the multi-user capability, the whole thing quickly becomes confusing.

![dropdown](https://user-images.githubusercontent.com/24696577/53565935-23313180-3b5b-11e9-9b18-21fa0faddb48.png)

**Comment by ghost** [comment]
This is possible but the user would have to remember their login username... and might be problematic
- maybe have this as an option so the site Admin can select dropdown or input field?

We'll consider this for a future update. 
5.3 is ready to ship so this will have to wait a little

**Comment by oliver-77** [comment]
An option to make this selectable in the admin area is a good compromise in my opinion. So everybody can decide for himself what he wants to see.

**Comment by ghost** [comment]
DONE - ready for next update

Allow option for input on login username instead of dropdown - the select is now an input with a datalist
