### ISSUE TITLE
[Pulse 5.3] The blog search shows content from the admin area

### ISSUE THREAD

**Issue by oliver-77** [yuzoolcode/pulsecms-tracking#95]
If you use blog search, content from the admin area will be displayed.

![search](https://user-images.githubusercontent.com/24696577/53683088-1ea47e80-3cfd-11e9-9096-c08c5a7e56a8.png)

**Comment by ghost** [comment]
Those need to be omitted, thanks for the report

**Comment by ghost** [comment]
Plugged in a fix for this - The blog search shows content from the admin area
The output removes blocks not in use, and draft entries.

This will be out in the next update - 5.3.2
