### ISSUE TITLE
[Pulse 5.3] Problems with OGP images

### ISSUE THREAD

**Issue by oliver-77** [yuzoolcode/pulsecms-tracking#96]
Something must be entered in the OGP Standard Image field, otherwise no OGP image will be entered in the source code, even if a featured image is set.
The field is empty by default.

![ogp](https://user-images.githubusercontent.com/24696577/53683599-0f283400-3d03-11e9-863c-9af18de6df3b.png)

Manual setting of the OGP image with 
`{{ogp:image:content/media/gallery1/city.jpg}}`
does not work.

![ogp](https://user-images.githubusercontent.com/24696577/53683565-94f7af80-3d02-11e9-84b6-a4b20d7089f9.png)

**Comment by ghost** [comment]
Good catch - for now something will need to be added until we can patch this

**Comment by ghost** [comment]
This has been fixed.

The OGP is now using /media/branding/pulse5_banner.jpg as the default.

The next version will have this in it (5.3.1) and will also include some other OGP improvements to be mentioned soon.
