### ISSUE TITLE
[Pulse 5.3] Set utf encoding to the dashboard dates

### ISSUE THREAD

**Issue by oliver-77** [yuzoolcode/pulsecms-tracking#97]
https://forum.pulsecms.com/t/after-update-to-5-3/1373/3?u=oliver

**Comment by ghost** [comment]
The Blocks dates work here locally on apache and on Linux too so it could be something else. Will need more testing before the next update…

Thanks for posting

**Comment by oliver-77** [comment]
I think it has something to do with the server settings. There are a lot of differences in the configuration. Depending on what is set in Apache, a standard charset is provided or not.

**Comment by ghost** [comment]
This is an interesting bug.  It seems to be a known bug
https://stackoverflow.com/questions/8993971/php-strftime-french-characters

So the setlocale call needs to use the UTF8 aware argument and the page content type header needs to be the UTF8 version.

**Comment by oliver-77** [comment]
Yeah, it actually looks like that's a bug.

So far it seems to work with my solution, I switched languages several times and couldn't find anything negative with utf8_encode before strftime.

**Comment by ghost** [comment]
I can replicate the bug. I've extended the number of locales in to use. This doesn't help much. So it might be something else. Worse case is that something like https://www.php.net/manual/en/book.intl.php might be needed ?

**Comment by ghost** [comment]
This is a weird one.

I haven't tried your fix @oliver-77  since I'm not sure what utf_encode will do to strings that are already correctly encoded. See https://www.php.net/manual/en/function.utf8-encode.php

Setting the server locale is dependent on the OS.

The last update added a range of locales per language and that range tries to cover windows and unix/linux systems. With that change I can see the bug on windows. The unit test passes, so its setting one of the fallback options.

The current locales per language are set as follows for the next update:

> "czech" => ["Czech_Czech Republic.1250", "cs_CZ.UTF-8", "cs_CZ.utf8", "cs_CZ", "cs"]
> 
> "deutsch" => ["German_Germany.1252", "de_DE.UTF-8", "de_DE.utf8", "de_DE", "de"]
> 
> "dutch" => ["Dutch_Netherlands.1252", "nl_NL.UTF-8", "nl_NL.utf8", "nl_NL", "nl"]
> 
> "english" => ["American_USA.1252", "en_US.UTF-8", "en_US.utf8", "en_US", "en"]
> 
> "hungarian" => ["Hungarian_Hungary.1250", "hu_HU.UTF-8", "hu_HU.utf8", "hu_HU", "hu"]
> 
> "japanese" => ["Japanese_Japan.932", "ja_JP.UTF-8", "ja_JP.utf8", "ja_JP", "ja"]
> 
> "polish" => ["Polish_Poland.1250", "pl_PL.UTF-8", "pl_PL.utf8", "pl_PL", "pl"]
> 
> "portuguese_BR" => ["Portuguese_Brazil.1252", "pt_BR.UTF-8", "pt_BR.utf8", "pt_BR", "pt"]
> 
> "romanian" => ["Romanian_Romania.1250", "ro_RO.UTF-8", "ro_RO.utf8", "ro_RO", "ro"]
> 
> "russian" => "Russian_Russia.1251", "ru_RU.UTF-8", "ru_RU.utf8", "ru_RU", "ru"]
> 
> "slovak" => ["Slovak_Slovakia.1250", "sk_SK.UTF-8", "sk_SK.utf8", "sk_SK", "sk"]
> 
> "spanish" => ["Spanish_Spain.1252", "es_ES.UTF-8", "es_ES.utf8", "es_ES", "es"]


I'll test some more and see whats going on.

**Comment by ghost** [comment]
The German date bug is no closer to a solution. 

I've verified that running UTF8 encode on a string with UTF8 characters generates some mangled characters. I tried some string conversion with iconv and mbstring convert without any success. It might be that the locale setting is using the wrong value. I'll test that again and try the intl library next for the date formatting. It's possible that this is Windows related and won't show on linux.

The downside of the intl library is that its another dependency.

**Comment by ghost** [comment]
After implementing and testing, the date formatter in the intl PHP module does work for German dates.

**Comment by ghost** [comment]
This is not done (not finished) beyond testing.

Adding PHP intl as a dependency would need some changes to the install and so on.

One complication is that the dateFormatter uses a different format to that of strftime, so it needs some glue code.

**Comment by ghost** [comment]
I think this one should be taken off the list now? 

We made some changes for it, but those didn't seem to help much. 

It's not clear whats going on - https://www.php.net/manual/en/book.intl.php is a new dependency and might work.
