### ISSUE TITLE
Preview error when a Blog Post is in draft mode

### ISSUE THREAD

**Issue by oliver-77** [yuzoolcode/pulsecms-tracking#98]
When trying to preview a blog post that is in draft mode, an error is thrown.
It would be good if you could preview the post without publishing it.

`Fatal error: Uncaught LogicException: An invariant has failed in D:\webserver\www\pulse53\pulsecore\dbc.php:12 Stack trace: #0 D:\webserver\www\pulse53\inc\tags\blog.php(41): pulsecore\invariant(false) #1 D:\webserver\www\pulse53\index.php(315): include('D:\\webserver\\ww...') #2 {main} thrown in D:\webserver\www\pulse53\pulsecore\dbc.php on line 12`

**Comment by ghost** [comment]
Preview in draft mode should already be working, this might be a new bug since some changes have been made to the blog logic - thanks for reporting

**Comment by ghost** [comment]
Draft mode for blog items seems to be working. There can't be a dash between draft and the blog ID since that causes problems with the url prefix parsing. 

This was fixed in 5.0.2:
https://github.com/yuzoolcode/pulsecms-tracking/issues/4

- What do your blog id / names look like?
- Could need more work if still happening 

Thanks

**Comment by oliver-77** [comment]
Okay, I guess that was the mistake. It usually looks like that to me:  `draft-8.`

If I now rename the post to `draft8` then it does indeed work.

Okay then the bug can be closed, then I would regard it as a feature request. 😉
I think it looks clearer if there is a separation between the word draft and the blogname.
Even better would be a button that sets this automatically.

**Comment by oliver-77** [comment]
What I just noticed, when I put the date into the future, a `draft-` is automatically put in front of the name, so that's not right either.

If I put the post in draft mode before and then change the date into the future, the whole thing even looks like this:
![draft](https://user-images.githubusercontent.com/24696577/54095446-ab0f0b00-43a7-11e9-8bec-c66ad48b2994.png)


So still a small bug 😀

**Comment by ghost** [comment]
> Even better would be a button that sets this automatically.

- Button is a good idea

- thanks for the bug report, this needs testing :)

**Comment by ghost** [comment]
Preview error when blog is in draft mode has been fixed for the next update.

Fix includes pulse core code changes and a new line in the htaccess:

```
# draft blog pages
RewriteRule ^blog-draft-([^-]*)? "index.php?p=blog-draft-$1" [L,Q
```SA]
