### ISSUE TITLE
Pulse 5.3.1 {{recentposts_visual}} - Issues with title link and image path.

### ISSUE THREAD

**Issue by ezchile** [yuzoolcode/pulsecms-tracking#99]
The 'recentposts_visual_card_title' link doesn't resolve to the full blog url that it refers to.

Also, the path to the first image appears to be getting corrupted upon parsing.

**Comment by ghost** [comment]
Thanks for reporting, will need further testing

**Comment by ghost** [comment]
Posted more here by @ezchile 
Thanks:
https://forum.pulsecms.com/t/pulse-5-3-1-recentposts-visual-issues/1388

**Comment by ghost** [comment]
Fixed as per your suggestion @ezchile  - thanks and will be out in the next release :)
